### PR TITLE
Ensure that plugs are enabled before we get stats from them.

### LINKED ISSUE #6459: Calculation of Destiny 2 armor Base Stats incorrectly includes disabled Armor Mods
**What version of DIM are you using?**
Version 6.48.0 (release), built on 18/01/2021, 02:47:29
Orange DIM icon.

**What Browser and OS are you using?**
Firefox 84.0.2 (64-bit)

**Describe the bug and how to make it happen**
Calculation of base stats incorrectly includes Armor Mods that are disabled.
Capture
This armour has 7 Resilence and 62 total base stats; the Armor Mods are disabled and do not affect the stats.
It is calculated as -3 Resilience and 52 total base stats. (Affects the web application and .csv export.)
In this case the Armor Mods were disabled upon the release of Beyond Light, which increased the energy costs.

### PR DESCRIPTION
**Pull request by ryan-rushton**
I think this should fix the following issue.

 I went digging for anywhere we get plugged.stats and guarded them. Also I added a couple more guards in the stats file, I thought the mod stat calculation would have gotten them though...

Fixes #6459

### CODE REVIEW

File: src/app/inventory/store/stats.ts [hunk 1]
```diff
@@ -185,7 +185,7 @@ function buildClassItemStatsFromMods(
   }
 
   for (const socket of modSockets) {
-    if (socket?.plugged?.stats) {
+    if (socket.plugged?.enabled && socket?.plugged?.stats) {
```
Comment (bhollis) [inline src/app/inventory/store/stats.ts:188]: You don't need all the ?. in the second condition because it's guaranteed that `socket.plugged` exists at that point.

**Review by bhollis — APPROVED** [review]

File: src/app/inventory/store/stats.ts (hunk 1 above)
Comment (ryan-rushton) [reply src/app/inventory/store/stats.ts]: Done, missed that.
