### PR TITLE
Fix mod selection from socket.

### LINKED ISSUE #7470: Selecting a second mod slot from the GeneratedSet mods erases the first
1. Go to Loadout Optimizer
2. Click on one of the mod slots on one of the generated sets and choose a mod
3. Click on a second mod slot on the same item of that set, and choose another mod
4. The first mod is gone

You'll notice that even in step 3, the original selected mod isn't there. I tracked it as far as `PlugDrawer#createInternalSelectedState` but I'm honestly not sure what's going on there.

### PR DESCRIPTION
**Pull request by ryan-rushton**
Fixed issue where selecting mods from the Mod Picker, opened from an item socket, would clear other mod selections.

It is correct that this bug came from the work to handle artificer mods but I think the root cause is better attributed to the mod picker not intelligently sending in selected mods that are actually visible in the mod picker.

This fixes that by only sending in mods that are actually visible, and when the user accepts the selection we append all the selected mods that were not visible to the result.

Fixes #7470

### CODE REVIEW

**Comment by ryan-rushton** [comment]
@bhollis I also took another pass at the docs for that internal state business in the plug drawer, so let me know if it is any better.

File: src/app/loadout/plug-drawer/PlugDrawer.tsx [hunk 1]
```diff
@@ -243,25 +252,35 @@ export default function PlugDrawer({
   );
 }
 
+/**
+ * A map of plugSetHashes to the selected plugs for that plugSetHash.
+ */
+type InternalSelectedState = {
+  [plugSetHash: number]: PluggableInventoryItemDefinition[] | undefined;
+};
```
Comment (ryan-rushton) [inline src/app/loadout/plug-drawer/PlugDrawer.tsx:260]: I was thinking about it and maybe we are better off expecting this data structure as our`initiallySelected` prop. 

The issue as I see it is we have a flat list of mods in the API and now we need those mods indexed by a `plugSetHash` and we just need to find the most appropriate point to do that. My initial cut was to hide it away from implementers of this `PlugDrawer` component so it is only done once. But maybe it makes more sense for the consumer of the component to decide how that is done. 

Thoughts?

**Review by nev-r — APPROVED** [review]
