### PR TITLE
override plurals; add i18n language object

### LINKED ISSUE #8230: Search displays wrong total while on any locale but english
### DIM Version

Version 7.9.0 (release), built 21.03.2022, 05:34:41

### Browser Details

Safari 15.4 (17613.1.17.1.6)

### OS Details

macOS Monterey

### Describe the bug

I opened DIM in english language
I searched `tag:junk is:dupelower`
I got total of 47 items
image

I opened DIM in any other language
I searched `tag:junk is:dupelower`
I got total of 1 item
image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by delphiactual**
Closes #8230

### CODE REVIEW

File: src/app/search/search-filters/freeform.tsx [hunk 1]
```diff
@@ -8,9 +9,7 @@ import memoizeOne from 'memoize-one';
 import { FilterDefinition } from '../filter-types';
 
 /** global language bool. "latin" character sets are the main driver of string processing changes */
-const isLatinBased = memoizeOne((language: string) =>
-  ['de', 'en', 'es', 'es-mx', 'fr', 'it', 'pl', 'pt-br'].includes(language)
-);
+const isLatinBased = memoizeOne((language: string) => DIM_LANG_INFOS[language].latinBased);
```
Comment (delphiactual) [inline src/app/search/search-filters/freeform.tsx:12]: does this still need to be memoized?

File: src/app/i18n.ts [hunk 2]
```diff
@@ -100,5 +89,39 @@ export function initi18n(): Promise<unknown> {
         }
       }
     );
+    if (DIM_LANG_INFOS[lang]?.pluralOveride) {
+      i18next.services.pluralResolver.addRule(lang, i18next.services.pluralResolver.getRule('en'));
+    }
   });
 }
+
+function getLanguagePath(language: string) {
```
Comment (nev-r) [inline src/app/i18n.ts:98]: this function serves no purpose except to do a dictionary lookup, i'm not sure why it needs to be a function instead of just an object

if the goal is to make `loadPath` less messy, the languagePath object should be moved out to top level. it serves no purpose to create the object inside a function

File: src/app/i18n.ts [hunk 3]
```diff
@@ -100,5 +89,39 @@ export function initi18n(): Promise<unknown> {
...
+    ptBR: ptBR,
+    zhCHT: zhCHT,
+    zhCHS: zhCHS,
+  };
+
+  return languagePath[language] as string;
+}
+
+function validLocales() {
+  return DIM_LANGS.map((lang) => {
```
Comment (nev-r) [inline src/app/i18n.ts:119]: you could do

`lang.replace(/(?<=[a-z])(?=[A-Z])/,'-')`

to add a hyphen to any lowerUPPER transition

File: src/app/i18n.ts [hunk 4]
```diff
@@ -100,5 +89,39 @@ export function initi18n(): Promise<unknown> {
...
+    esMX: esMX,
+    ptBR: ptBR,
+    zhCHT: zhCHT,
+    zhCHS: zhCHS,
+  };
+
+  return languagePath[language] as string;
+}
+
+function validLocales() {
```
Comment (nev-r) [inline src/app/i18n.ts:118]: instead of this being a function, you could generate this at top level once, just like how DIM_LANGS is created

File: src/app/i18n.ts (hunk 2 above)
Comment (delphiactual) [reply src/app/i18n.ts]: there was more in the function before I committed as I left the office...

File: src/app/i18n.ts [hunk 5]
```diff
@@ -15,24 +15,26 @@ import zhCHS from 'locale/zhCHS.json';
 import zhCHT from 'locale/zhCHT.json';
 import { humanBytes } from './storage/human-bytes';
 
+export const DIM_LANG_INFOS = {
+  de: { pluralOveride: false, latinBased: true },
```
Comment (bhollis) [inline src/app/i18n.ts:19]:
```suggestion
  de: { pluralOverride: false, latinBased: true },
```

File: src/app/search/search-filters/freeform.tsx (hunk 1 above)
Comment (bhollis) [reply src/app/search/search-filters/freeform.tsx:12]: No, I don't think so.

File: src/app/i18n.ts (hunk 5 above)
Comment (delphiactual) [reply src/app/i18n.ts:19]: doh

**Review by bhollis — APPROVED** [review]
