### PR TITLE
Exotic Artifice fixups

### LINKED ISSUE #10503: Ensure mod assignment doesn't try to plug artifice mods in exotic armor 1.0
LO doesn't, but Loadouts themselves do support Armor 1.0 and may include them in mod assignment. If this ever assigns an artifice mod to an exotic 1.0 that can't have an artifice slot, `pickPlugPositions` can crash the app later.

_Originally posted by @robojumper in https://github.com/DestinyItemManager/DIM/pull/10499#discussion_r1628981637_

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #10503.
Fixes https://discord.com/channels/316217202766512130/333464468241514497/1248268767159648390
Adds costs to Mod Assignment Sheet and tries to minimize costs 
grafik

### CODE REVIEW

File: src/app/dim-ui/EnergyIncrements.tsx [hunk 1]
```diff
@@ -6,6 +6,8 @@ import { MAX_ARMOR_ENERGY_CAPACITY } from 'app/search/d2-known-values';
 import clsx from 'clsx';
 import { PressTip } from './PressTip';
 
+// TODO special display for T10 -> T10 + exotic artifice?
```
Comment (bhollis) [inline src/app/dim-ui/EnergyIncrements.tsx:9]: Definitely. We could just use the cipher icon?

**Review by bhollis — APPROVED** [review]
