### PR TITLE
Use collectible matching for vendor armor collections checkmarks

### LINKED ISSUE #7023: Ada not included when filtering Vendors for uncollected items
### DIM Version

Version 6.81.0.1000691 (beta), built on 9/8/2021, 9:04:55 AM

### Browser Details

Chrome 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Ada is currently selling the Insight armor sets:
image

I do not have this set in my collection:
image

However, when I filter the Vendor page to "Only show uncollected items," the items do not appear, and Ada is filtered out of the list:
image

### Logs

_No response_

### LINKED ISSUE #9930: Collections Blue Check missing from vendor armor
### DIM Version

Version 7.87.0.1002969 (beta), built on 9/28/2023, 6:37:56 PM

### Browser Details

Opera 102.0.0.0 (and all other browsers)

### OS Details

Windows 10

### Describe the bug

The missing checkmark has been throwing me off for a while considering it's present on essentially every other vendor item. At the very least, it would be nice to have the "This item is unlocked in collections." text on the popup after clicking on the armor like how it works in the Records tab. 

### Vendor inventory:
image
### In-game screenshot showing it's unlocked:
image

### Records tab item popup:
image
### Vendor item popup:
image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #7023.
Fixes #9930.

Generalizes the code from universal ornaments to find a related collectible for armor sold by vendors too. I have all that armor unlocked anyway, so I can't test the "not collected" case but it does mark them as collected for me.

### CODE REVIEW

File: src/app/records/universal-ornaments/universal-ornaments.tsx [hunk 1]
```diff
@@ -125,29 +126,23 @@ function identifyPlugSets(defs: D2ManifestDefinitions): { [classType: number]: n
...
     [DestinyClass.Titan]: { classType: DestinyClass.Titan, sets: {}, name: '', icon: '' },
     [DestinyClass.Hunter]: { classType: DestinyClass.Hunter, sets: {}, name: '', icon: '' },
     [DestinyClass.Warlock]: { classType: DestinyClass.Warlock, sets: {}, name: '', icon: '' },
   };
 
+  const findCollectibleArmorParentNode = (collectibleHash: number | undefined) => {
+    if (collectibleHash) {
+      const collectible = defs.Collectible.get(collectibleHash);
+      return collectible.parentNodeHashes
+        ?.map((nodeHash) => defs.PresentationNode.get(nodeHash))
```
Comment (bhollis) [inline src/app/records/universal-ornaments/universal-ornaments.tsx:141]: Out of paranoia, probably handle the case where either the collectible def or presentation node def are missing.

**Review by bhollis — APPROVED** [review]
Great, this makes the collections indicators way more useful.
