### PR TITLE
Removed WebKit bug 166879 workaround

### LINKED ISSUE #7316: is it time to un-workaround webkit bug 166879?
@bhollis 
https://bugs.webkit.org/show_bug.cgi?id=166879
this is confirmed fixed back in 2017 and safari version 10?
i think we are fine within our supported versions now

### PR DESCRIPTION
**Pull request by Supersonicboss1**
https://bugs.webkit.org/show_bug.cgi?id=166879
As the issue states, this bug was fixed back in 2017 and safari v10, which is no longer supported by DIM. This re-adds the anonymous arrow functions instead of unneeded function declarations.
Fixes #7316

### CODE REVIEW

File: src/app/manifest/d1-manifest-service.ts [hunk 1]
```diff
@@ -96,7 +96,20 @@ function loadManifestRemote(version: string, path: string): ThunkResult<object>
       const manifest = await (response.ok ? response.json() : Promise.reject(response));
 
       // We intentionally don't wait on this promise
-      saveManifestToIndexedDB(manifest, version);
+      async () => {
```
Comment (nev-r) [inline src/app/manifest/d1-manifest-service.ts:99]: fwiw this code as written does not actually run the function, just creates it

**Comment by Supersonicboss1** [comment]
> Thanks for taking this on, but looking at the change I think I like it broken out into functions better. So maybe all we need to do is remove that one comment.

I do agree, it looks cleaner broken up into functions. should I close this PR, or edit it to remove the comments?

**Comment by bhollis** [comment]
You can do either!

**Comment by Supersonicboss1** [comment]
Done! Commit was reverted and bug warnings were removed.
