### PR TITLE
Expand lookup table of items to allow for search loadouts containing consumables

### LINKED ISSUE #10013: Transfer search cannot transfer consumables
Bulk transfer uses loadouts. Consumables are uninstanced

https://github.com/DestinyItemManager/DIM/blob/a37dbd72bc7a1514df1f63c427fb68af7aae752b/src/app/loadout-drawer/loadout-utils.ts#L619-L628

but D2 doesn't allow consumables in loadouts

https://github.com/DestinyItemManager/DIM/blob/a37dbd72bc7a1514df1f63c427fb68af7aae752b/src/app/utils/item-utils.ts#L170-L179

so we fail resolving the consumable in loadout application.

### PR DESCRIPTION
**Pull request by bhollis**
Fixes #10013

### CODE REVIEW

File: src/app/loadout-drawer/loadout-utils.ts [hunk 1]
```diff
@@ -644,7 +647,7 @@ export function getUninstancedLoadoutItem(
   storeId: string | undefined,
 ) {
   // This is mostly for subclasses - it finds all matching items by hash and then picks the one that's on the desired character
-  const candidates = potentialUninstancedLoadoutItemsByHash(allItems).get(hash) ?? [];
+  const candidates = uninstancedItemsByHash(allItems).get(hash) ?? [];
```
Comment (robojumper) [inline src/app/loadout-drawer/loadout-utils.ts:650]: Subclasses are `instanced` technically but we call them uninstanced because we match by hash. This regresses subclass lookup.

Comment (robojumper) [reply src/app/loadout-drawer/loadout-utils.ts:651]: Oh also emblems... not sure if the instanced check in the lookup table buys us much

**Review by robojumper — APPROVED** [review]
