### PR TITLE
fix: safe area is respected for pages

### LINKED ISSUE #10445: bug: inline menu does not respect safe area
### DIM Version

Version 8.19.2 (release), built on 5/15/2024, 5:53:53 AM

### Browser Details

Safari/WKWebView for iOS

### OS Details

iOS 17.5

### Describe the bug

The left/right safe area is not respected on certain pages. As a result, content can run into the notch on iOS devices when in landscape.

**Steps to reproduce:**

1. Open DIM on an iOS device.
2. Open the "Settings" page. Observe that the inline menu on the page bleeds over into the safe area. (also happens with the About page).

**Expected Behavior:**

I expect content such as text to not bleed over into the safe area.

**Actual Behavior:**

Text content is bleeding over into the safe area.

CleanShot 2024-05-20 at 21 13 44

### Logs

_No response_

### PR DESCRIPTION
**Pull request by liamdebeasi**
resolves #10445

DIM has two components that render routes, `App` and `Destiny`. The `Destiny` component has CSS that allows the rendered page content to not bleed into the safe area. Routes only rendered in the `App` component do not have this same CSS. As a result, certain pages such as Settings do not respect the safe area.

The `App` component renders the `Destiny` component (which then renders other pages), so setting the safe area styles on the `App` component we can ensure that all pages account for the safe area.

| `main` | branch |
| - | - |
| CleanShot 2024-05-20 at 21 19 35 | CleanShot 2024-05-20 at 21 18 59 |
| CleanShot 2024-05-20 at 21 24 59 | CleanShot 2024-05-20 at 21 25 14 |

Note: I think I still need to add an entry to the CHANGELOG according to the [contributing guide](https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md). I didn't see a new entry for the next release, and I wasn't sure what to put for the release date when adding a new release heading. If you could provide some guidance on what to put there, I'll be happy to make the changes!

### CODE REVIEW

File: src/app/shell/Destiny.m.scss [hunk 1]
```diff
@@ -1,5 +1,3 @@
 .content {
   user-select: none;
```
Comment (liamdebeasi) [inline src/app/shell/Destiny.m.scss:2]: This line needs to stay where it is. Otherwise users will no longer be able to select text on the "About" page which is a behavior that currently exists in DIM.

**Comment by bhollis** [comment]
Thanks for the update. DIM isn't really meant to be used in landscape mode on mobile, but this should improve the experience on those pages.

If you'd like to update the CHANGELOG, you can add your update under `## Next`. Or, I can do it after merge.

**Review by bhollis — APPROVED** [review]

**Review by lowPolySkeleton — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Thanks! I updated the CHANGELOG in https://github.com/DestinyItemManager/DIM/pull/10444/commits/cfa6bb2239ea3a9f8a75c8f1d49b14f1f6adf863.
