### PR TITLE
fix(popover): dropdown does not flicker on firefox

### LINKED ISSUE #9925: Dropdown hover selection is weird on Firefox
Maybe a Firefox bug, but we should see if we can work around it.

### PR DESCRIPTION
**Pull request by liamdebeasi**
resolves #9925

**Background**

The `usePopper` hook uses [useLayoutEffect](https://github.com/DestinyItemManager/DIM/blob/7dd043fb65940312efb5bc368329d44732590d5f/src/app/dim-ui/usePopper.ts#L141-L163). Whenever `useLayoutEffect` runs, the popover is either created or destroyed and then re-created. This hook has no dependencies, so it runs any time its parent component re-renders.

This triggers a quirk in Firefox on hover since the popover is destroyed and re-created on each hover (since hovering causes a state change via Downshift). More info about the issue can be found [here](https://github.com/DestinyItemManager/DIM/issues/9925#issuecomment-2249265523).

-------

**The Fix**

To fix this, I updated `usePopper` to accept a list of dependencies that are then passed to `useLayoutEffect`. This ensures that `useLayoutEffect` only runs when the deps change. This is important for popovers that are added to the DOM on load but do not have any content (and thus have a dimension of 0x0). Since the content has a dimension of 0x0, Popper cannot position the popover correctly. Once the popover is opened, the content is added, and we need to re-run the hook so Popper can reposition the popover correctly.

-----

**Testing**

The following components should be tested since they use `usePopper`:

* `SymbolsPicker`
* `ItemPopup`
* `StoreHeading`
* `Select`
* `PressTip`
* `Dropdown`

----

**Other Info**

This fix should also provide a slight performance boost since DIM no longer needs to destroy and re-create the popover as often as it used to.

### CODE REVIEW

File: src/app/dim-ui/usePopper.ts [hunk 1]
```diff
@@ -125,6 +126,13 @@ export function usePopper({
   /** Is this placed on a fixed item? Workaround for https://github.com/popperjs/popper-core/issues/1156. TODO: make a "positioning context" context value for this */
   fixed?: boolean;
   padding?: Padding;
+
+  /**
+   * An optional state variable. Use this to have popper recalculate the position of
+   * a popover when conditionally rendering the contents of the popover (thus
+   * causing the dimensions to potentially change).
+   */
+  state?: boolean;
```
Comment (liamdebeasi) [inline src/app/dim-ui/usePopper.ts:135]: Open to other names here. Wasn't sure what to go with, so just used "state" for now.

**Comment by bhollis** [comment]
Awesome, glad to see a fix for this.

Longer term I'd love to see us do #8374 (Switch to Floating UI) or even swap to a CSS anchor positioning polyfill (though the one polyfill I've seen so far is not great).

File: src/app/dim-ui/usePopper.ts [hunk 2]
```diff
@@ -160,5 +168,5 @@ export function usePopper({
     }
 
     return destroy;
-  });
+  }, [reference, contents, state]);
```
Comment (bhollis) [inline src/app/dim-ui/usePopper.ts:171]: My original idea behind having the layout effect fire on every update was that I don't know what (if anything) has changed about the contents, so I don't know when exactly to re-position. This is made especially complicated by the fact that popper seems to have some bugs around its lifecycle (which afaik are fixed in floating-ui).

Testing around a bit, I can see that uses of `Dropdown` appear broken with this change - for example, the menu you can access from the three dots in the search bar.

**Comment by bhollis** [comment]
Also if you're on the Discord, ping me and I'll add the contributor role for you.

File: src/app/dim-ui/usePopper.ts (hunk 2 above)
Comment (liamdebeasi) [reply src/app/dim-ui/usePopper.ts:171]: Thanks for testing! I'll go back and take another look. It's likely that I missed a case I was not considering before.

File: src/app/dim-ui/usePopper.ts [hunk 3]
```diff
@@ -160,5 +163,16 @@ export function usePopper({
...
+    contents,
+    reference,
+    arrowClassName,
+    menuClassName,
+    boundarySelector,
+    placement,
+    offset,
+    fixed,
+    padding,
+    deps,
```
Comment (liamdebeasi) [inline src/app/dim-ui/usePopper.ts:176]: React expects that all reactive values be listed as dependencies: https://react.dev/reference/react/useEffect#specifying-reactive-dependencies

File: src/app/dim-ui/usePopper.ts (hunk 2 above)
Comment (liamdebeasi) [reply src/app/dim-ui/usePopper.ts]: Ok I made some adjustments. The big change here is `usePopper` now accepts a dependency list. For the particular broken popovers you noted, both the `isOpen` state and the `items` list are listed as dependencies in addition to all the other deps in `usePopper`. This should resolve the problem you noted.

I opted to note touch the other `usePopper` implementations because they currently do not exhibit the reported bug.

File: src/app/dim-ui/usePopper.ts (hunk 3 above)
Comment (bhollis) [reply src/app/dim-ui/usePopper.ts:176]: Fair, though in practice many of these are immutable. Can't hurt, though.

What doesn't work is including `deps` directly like this - hooks' dependencies list won't recursively evaluate equality. So you probably want:
```suggestion
    contents,
    reference,
    arrowClassName,
    menuClassName,
    boundarySelector,
    placement,
    offset,
    fixed,
    padding,
    ...deps,
```

Comment (liamdebeasi) [reply src/app/dim-ui/usePopper.ts:176]: Ah yeah, so that causes a React warning since React can't statically analyze the dependencies that way. We can add a comment to ignore the rule, but wasn't sure if you'd be comfortable with that approach.

-----

I can also remove the other refs if they are immutable, though that will cause React to log another warning since it expects them to be included as dependencies. Similarly, we can add a comment to ignore the rule if you'd like.

Comment (bhollis) [reply src/app/dim-ui/usePopper.ts:176]: Probably the best would be to silence the warning about having a dynamic dependency list, but still include all the other dependencies.

Comment (liamdebeasi) [reply src/app/dim-ui/usePopper.ts]: All set!

**Review by bhollis — APPROVED** [review]
