### PR TITLE
Fix React error when sorting transmog bounties

### LINKED ISSUE #7630: (Transmog) bounties visually duplicated when switching between characters in the Vendors view
### DIM Version

Version 6.97.3 (release), built on 31.12.2021, 04:37:12, Version 6.97.3.1001131 (beta), built on 2.1.2022, 22:48:42

### Browser Details

Firefox 95.0.2

### OS Details

Windows 10

### Describe the bug

My Titan has exhausted his Transmog bounties from Ada-1, while my Hunter hasn't. Alternating between Titan and Hunter in the Vendors view results in this: 
grafik

### Logs

```shell
None relevant
```

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #7630.

### CODE REVIEW

File: src/app/vendors/d2-vendors.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ const vendorOrder = [
   VENDORS.BENEDICT,
   VENDORS.BANSHEE,
   VENDORS.DRIFTER,
-  VENDORS.ADA,
+  VENDORS.ADA_FORGE,
```
Comment (robojumper) [inline src/app/vendors/d2-vendors.ts:43]: cc @bhollis -- two of these vendors are deprecated, and Spider is in a different category now. What was the rationale behind the order back then?

Comment (bhollis) [reply src/app/vendors/d2-vendors.ts:43]: I think in the beginning it was just because the order from the API didn't make much sense compared to in-game. But we've done a lot about sorting and categorization since then, so this may no longer be relevant.

**Review by bhollis — APPROVED** [review]
