### PR TITLE
Account for already plugged mods in mod assignment.

### LINKED ISSUE #7549: DIM messes up mod positions, making it unable to do the full loadout
### DIM Version

6.96.0

### Browser Details

All browsers

### OS Details

All OSs 

### Describe the bug

Loadouts often applies mods in the wrong slots and runs out of energy space.

For example, I have the current PvP loadout:

Void helmet: HC targetting + Sniper targetting 

Stasis gauntlets: Discipline +  Fastball + Sniper dexterity

Arc chest: Discipline +  HC unflinching + Radiant Light

Solar legs: Discipline +  Sniper scavenger

Arc class: Discipline +  Outreach + Powerful Friends

then, I have another loadout that uses some of those pieces for another type of loadout (think Protective Light in the helmet, Concussive Dampener in the chest, etc)

Without fail, DIM will slot Radiant Light in the class item and Powerful Friends in the chest item, which leaves it unable to slot the Discipline mod in the chest item because Powerful Friends + HC unflinching = 8 energy. It then also leaves Concussive Dampener in there.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ryan-rushton**
This should make a few people happy.

## Beta

Screen Shot 2021-12-29 at 7 11 43 pm

### This change and my in game assignment

Screen Shot 2021-12-29 at 7 11 26 pm

Closes #7549

### CODE REVIEW

File: src/app/loadout/mod-assignment-utils.ts [hunk 1]
```diff
@@ -283,13 +306,19 @@ export function fitMostMods(
           // The same amount of unassigned and active mods but the assignment is cheaper
           (unassignedModCount === assignmentUnassignedModCount &&
             totalActiveConditionalMods === assignmentActiveConditionalMods &&
-            energyUsedAndWasted <= assignmentEnergyCost)
+            energyUsedAndWasted < assignmentEnergyCost) ||
+          // The assignment costs the same but we are changing less mods
```
Comment (bhollis) [inline src/app/loadout/mod-assignment-utils.ts:310]:
```suggestion
          // The assignment costs the same but we are changing fewer mods
```

**Review by bhollis — APPROVED** [review]
