### PR TITLE
Negative Stat Support and Optimiser to use DimStat.base.

### LINKED ISSUE #4890: negative stats support
stubbing this because i've been poking at it, but slowly.
negative stat mods result in some weird behaviors, a -10 can render as a +10 bar graph on the class item, they don't seem to work right in LO, they display the wrong Total stat when equipped, etc

not all of this is exactly solvable because we're sent back a 0-capped version of the armor stat. the mod's contribution to the item, and the item's contribution to overall character stat value, may not be correct if affected by this cap. but some things can be tuned up.

### LINKED ISSUE #5381: Loadout Optimizer is not ignoring stat penalties on seasonal mods
(Issue found on beta version 6.16.1.7400)

I noticed that the Loadout Optimizer is not ignoring seasonal mod stat penalties, and also is incorrectly calculating those values if the penalty is greater than the stat on the armour piece it is equipped to.

Here are my stats without any mods equipped - for reference my recovery stat here is 39/100
image

If I equip the 'Stacks on Stacks' mod (-10 recovery) on my helmet (base recovery +7) the recovery value in the optimizer doesn't change:
image

However, if I switch the mod to my chest (base recovery +19), the recovery value in the optimizer changes:
image

I assume this is because DIM doesn't know that armour can potentially provide negative stat bonuses now in certain configurations (e.g. the helmet with Stacks on Stacks equipped is providing -3 recovery to the total stat).

In fairness the in-game interface is also pretty confusing with this - the totals are calculated correctly but the individual armour piece stats don't cope with the negative numbers properly.

Another strange behaviour I noticed is with the 'Charge Harvester' mod. The in game description says '-10 to the stat that governs your class ability recharge rate', but DIM is interpreting this as -10 to mobility, resilience and recovery:

image

### LINKED ISSUE #5440: Loadout Optimizer not working correctly with seasonal MODs
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?
Orange - 6.19.0
Blue - 6.19.0.7497

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?
Win 10 Home
Blue - App
Orange - Chrome, also tried Edge

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

In the Loadout optimizer for my hunter:
I added Taken Armaments, Taken Invigoration, Hive Repurposing, and Hive Armaments all from the seasonal mods, also tried class armor, and I expected to see builds but it says "no builds found". I can take away any two and it will give me builds.

I can lock in some great hunt, bladesmith, and GOS armor and it will then give me some builds. Also it doesen't seem to take into account that my capes can hold these seasonal mods. 

Thank you for all you do here!

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
instrument.ts:129 Sync: Storage will not be cleared except by explicit user action.
instrument.ts:129 Sync: DIM is using 37.13 MB total out of 279.08 GB in storage quota (0%).
instrument.ts:129 DIM v6.19.0.7497 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:129 Load accounts from IDB
/index.html?utm_source=homescreen:1 A cookie associated with a cross-site resource at http://bungie.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/index.html?utm_source=homescreen:1 A cookie associated with a cross-site resource at http://www.bungie.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
2263eddcb82daefb75.js:1 Refused to load the script 'https://loungesrc.net/optout/get?jsonp=__mtz_cb_800623988&key=2263eddcb82daefb75&t=1594223792412' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' data: 'report-sample' https://apis.google.com https://www.google-analytics.com https://platform.twitter.com https://cdn.syndication.twimg.com https://opencollective.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

script @ 2263eddcb82daefb75.js:1
/index.html?utm_source=homescreen:1 Refused to load the image 'https://loungesrc.net/metric/?mid=&wid=51807&sid=&tid=8803&rid=LAUNCHED&t=1594223792410' because it violates the following Content Security Policy directive: "img-src 'self' data: https://www.bungie.net https://ssl.google-analytics.com https://www.google-analytics.com https://csi.gstatic.com https://opencollective.com https://syndication.twitter.com https://platform.twitter.com https://*.twimg.com/ https://*.googleusercontent.com/".

/index.html?utm_source=homescreen:1 Refused to load the image 'https://loungesrc.net/metric/?mid=&wid=51807&sid=&tid=8803&rid=LOADED&custom1=beta.destinyitemmanager.com&custom2=%2Findex.html&t=1594223792412' because it violates the following Content Security Policy directive: "img-src 'self' data: https://www.bungie.net https://ssl.google-analytics.com https://www.google-analytics.com https://csi.gstatic.com https://opencollective.com https://syndication.twitter.com https://platform.twitter.com https://*.twimg.com/ https://*.googleusercontent.com/".

/index.html?utm_source=homescreen:1 Refused to load the image 'https://loungesrc.net/metric/?mid=&wid=51807&sid=&tid=8803&rid=BEFORE_OPTOUT_REQ&t=1594223792412' because it violates the following Content Security Policy directive: "img-src 'self' data: https://www.bungie.net https://ssl.google-analytics.com https://www.google-analytics.com https://csi.gstatic.com https://opencollective.com https://syndication.twitter.com https://platform.twitter.com https://*.twimg.com/ https://*.googleusercontent.com/".

/index.html?utm_source=homescreen:1 Refused to load the image 'https://loungesrc.net/metric/?mid=&wid=51807&sid=&tid=8803&rid=FINISHED&custom1=beta.destinyitemmanager.com&t=1594223792413' because it violates the following Content Security Policy directive: "img-src 'self' data: https://www.bungie.net https://ssl.google-analytics.com https://www.google-analytics.com https://csi.gstatic.com https://opencollective.com https://syndication.twitter.com https://platform.twitter.com https://*.twimg.com/ https://*.googleusercontent.com/".

instrument.ts:129 globalSettings Object
Grammarly.js:2 [DEFAULT]: WARN : Using DEFAULT root logger
t.printToConsole @ Grammarly.js:2
Grammarly.js:2 [WARNING] Using default timeseries implementation.
e.getRootMetric @ Grammarly.js:2
wishlist-file.ts:21 Parse wish list: 149.735107421875ms
instrument.ts:129 Refreshed wishlist, but it matched the one we already have
inventory:1 A cookie associated with a cross-site resource at http://loungesrc.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
manifest-service-json.ts:150 Load manifest: 1563.746826171875ms
instrument.ts:129 Saving profile data to IDB
d2-stores.ts:255 Process inventory: 146.94091796875ms
d2-stores.ts:259 Inventory state update: 815.453125ms
inventory:1 [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
wishlist-file.ts:21 Parse wish list: 135.35693359375ms
instrument.ts:129 Refreshed wishlist, but it matched the one we already have
d2-stores.ts:255 Process inventory: 114.5556640625ms
d2-stores.ts:259 Inventory state update: 230.9208984375ms
wishlist-file.ts:21 Parse wish list: 134.212890625ms
instrument.ts:129 Refreshed wishlist, but it matched the one we already have
d2-stores.ts:255 Process inventory: 113.54296875ms
d2-stores.ts:259 Inventory state update: 175.018798828125ms
instrument.ts:129 Object
instrument.ts:129 Object
instrument.ts:129 Object
instrument.ts:129 Object
instrument.ts:129 Object
instrument.ts:129 Object
instrument.ts:129 Object
instrument.ts:129 Object
instrument.ts:129 Object
6Reduced armor combinations from 14443520 to 1976836
d2-stores.ts:255 Process inventory: 113.17626953125ms
d2-stores.ts:259 Inventory state update: 34.889892578125ms
ProcessWorker-7589fc.worker.js:1 found 70 stat mixes after processing 1976836 stat combinations in 3094.235000000481 ms
instrument.ts:129 useProcess: worker time 3145.660000000149ms
instrument.ts:129 useProcess 3172.880000000121ms
ProcessWorker-7589fc.worker.js:1 found 70 stat mixes after processing 1976836 stat combinations in 3137.1449999987817 ms
instrument.ts:129 useProcess: worker time 3190.670000000042ms
instrument.ts:129 useProcess 3204.1049999989336ms
instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 0.7109375ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
instrument.ts:129 Saving profile data to IDB
ProcessWorker-7589fc.worker.js:1 found 104 stat mixes after processing 1976836 stat combinations in 3079.6399999999267 ms
instrument.ts:129 useProcess: worker time 3128.045000001206ms
instrument.ts:129 useProcess 3139.669999998645ms
instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 0.515380859375ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
instrument.ts:129 Saving profile data to IDB
ProcessWorker-7589fc.worker.js:1 found 70 stat mixes after processing 1976836 stat combinations in 3166.7099999995116 ms
instrument.ts:129 useProcess: worker time 3213.265000000247ms
instrument.ts:129 useProcess 3226.1850000013364ms
instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 0.4580078125ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
instrument.ts:129 Saving profile data to IDB
ProcessWorker-7589fc.worker.js:1 found 70 stat mixes after processing 1976836 stat combinations in 3100.545000001148 ms
instrument.ts:129 useProcess: worker time 3154.3249999994878ms
instrument.ts:129 useProcess 3164.5000000006985ms
10Reduced armor combinations from 28887040 to 1968128
instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 0.491943359375ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
instrument.ts:129 Saving profile data to IDB
ProcessWorker-7589fc.worker.js:1 found 96 stat mixes after processing 1968128 stat combinations in 3039.345000001049 ms
instrument.ts:129 useProcess: worker time 3086.720000001136ms
instrument.ts:129 useProcess 3098.7050000003073ms
ProcessWorker-7589fc.worker.js:1 found 89 stat mixes after processing 902720 stat combinations in 1348.809999999503 ms
instrument.ts:129 useProcess: worker time 1391.279999999795ms
instrument.ts:129 useProcess 1405.2050000010058ms
ProcessWorker-7589fc.worker.js:1 found 96 stat mixes after processing 1968128 stat combinations in 3091.4599999996426 ms
instrument.ts:129 useProcess: worker time 3137.3199999998324ms
instrument.ts:129 useProcess 3151.0099999995437ms
d2-stores.ts:255 Process inventory: 172.005859375ms
d2-stores.ts:259 Inventory state update: 54.60009765625ms
instrument.ts:129 Saving profile data to IDB
ProcessWorker-7589fc.worker.js:1 found 96 stat mixes after processing 1968128 stat combinations in 3148.3850000004168 ms
instrument.ts:129 useProcess: worker time 3217.4550000000745ms
instrument.ts:129 useProcess 3246.6349999995437ms
d2-stores.ts:255 Process inventory: 122.385986328125ms
d2-stores.ts:259 Inventory state update: 140.062255859375ms
ProcessWorker-7589fc.worker.js:1 found 96 stat mixes after processing 1968128 stat combinations in 3142.340000000331 ms
instrument.ts:129 useProcess: worker time 3195.1650000009686ms
instrument.ts:129 useProcess 3234.6699999999255ms
instrument.ts:129 Object
d2-stores.ts:255 Process inventory: 109.8310546875ms
d2-stores.ts:259 Inventory state update: 26.875ms
ProcessWorker-7589fc.worker.js:1 found 96 stat mixes after processing 1968128 stat combinations in 3123.60500000068 ms
instrument.ts:129 useProcess: worker time 3175.6800000001676ms
instrument.ts:129 useProcess 3204.6000000007916ms
ProcessWorker-7589fc.worker.js:1 found 0 stat mixes after processing 14560 stat combinations in 23.784999999406864 ms
instrument.ts:129 useProcess: worker time 75.99500000104308ms
instrument.ts:129 useProcess 89.28499999991618ms
ProcessWorker-7589fc.worker.js:1 found 89 stat mixes after processing 902720 stat combinations in 1354.1100000002189 ms
instrument.ts:129 useProcess: worker time 1396.3450000009034ms
instrument.ts:129 useProcess 1422.6650000000373ms
instrument.ts:129 Object
ProcessWorker-7589fc.worker.js:1 found 78 stat mixes after processing 451360 stat combinations in 767.0799999996234 ms
instrument.ts:129 useProcess: worker time 880.6550000009593ms
instrument.ts:129 useProcess 906.5749999992549ms
ProcessWorker-7589fc.worker.js:1 found 78 stat mixes after processing 451360 stat combinations in 741.5199999995821 ms
instrument.ts:129 useProcess: worker time 918.714999999851ms
instrument.ts:129 useProcess 931.3000000002794ms
ProcessWorker-7589fc.worker.js:1 found 78 stat mixes after processing 451360 stat combinations in 773.3700000007957 ms
instrument.ts:129 useProcess: worker time 818.0350000003818ms
instrument.ts:129 useProcess 829.5550000004005ms
ProcessWorker-7589fc.worker.js:1 found 76 stat mixes after processing 244296 stat combinations in 557.5649999991583 ms
instrument.ts:129 useProcess: worker time 591.6049999995157ms
instrument.ts:129 useProcess 603.5849999990314ms
instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 1.432861328125ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
ProcessWorker-7589fc.worker.js:1 found 77 stat mixes after processing 211344 stat combinations in 552.4499999992258 ms
instrument.ts:129 useProcess: worker time 591.3049999999348ms
instrument.ts:129 useProcess 598.5249999994412ms
instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 0.740966796875ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
2instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 1.883056640625ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
2instrument.ts:129 Saving profile data to IDB
reducer.ts:369 prepareUpdateQueue: 1.821044921875ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results Array(1) Array(1)
instrument.ts:129 Saving profile data to IDB
ProcessWorker-7589fc.worker.js:1 found 77 stat mixes after processing 211344 stat combinations in 534.5300000008137 ms
instrument.ts:129 useProcess: worker time 569.3000000009779ms
instrument.ts:129 useProcess 577.1249999997672ms
ProcessWorker-7589fc.worker.js:1 found 77 stat mixes after processing 211344 stat combinations in 561.969999998837 ms
instrument.ts:129 useProcess: worker time 624.1900000004098ms
instrument.ts:129 useProcess 647.9149999995716ms
instrument.ts:129 Saving profile data to IDB
d2-stores.ts:255 Process inventory: 147.53515625ms
d2-stores.ts:259 Inventory state update: 61.511962890625ms
ProcessWorker-7589fc.worker.js:1 Reduced armor combinations from 11623920 to 1968128
ProcessWorker-7589fc.worker.js:1 found 96 stat mixes after processing 1968128 stat combinations in 3122.7149999995163 ms
instrument.ts:129 useProcess: worker time 3173.5799999986775ms
instrument.ts:129 useProcess 3326.8250000001863ms
ProcessWorker-7589fc.worker.js:1 found 102 stat mixes after processing 207570 stat combinations in 572.9200000005221 ms
instrument.ts:129 useProcess: worker time 671.6550000000279ms
instrument.ts:129 useProcess 776.9849999987055ms
instrument.ts:129 Object
ProcessWorker-7589fc.worker.js:1 found 85 stat mixes after processing 5610 stat combinations in 129.76999999955297 ms
instrument.ts:129 useProcess: worker time 215.63000000058673ms
instrument.ts:129 useProcess 312.8349999987986ms
ProcessWorker-7589fc.worker.js:1 found 85 stat mixes after processing 5610 stat combinations in 132.660000001124 ms
instrument.ts:129 useProcess: worker time 210.8300000000745ms
instrument.ts:129 useProcess 230.29499999945983ms
instrument.ts:129 Object
2instrument.ts:129 Successfully updated auth token from refresh token.
ProcessWorker-7589fc.worker.js:1 found 92 stat mixes after processing 314160 stat combinations in 795.3150000012101 ms
instrument.ts:129 useProcess: worker time 852.399999999674ms
instrument.ts:129 useProcess 870.6800000001676ms
d2-stores.ts:255 Process inventory: 111.675048828125ms
d2-stores.ts:259 Inventory state update: 23.60888671875ms
ProcessWorker-7589fc.worker.js:1 found 92 stat mixes after processing 314160 stat combinations in 786.7999999998574 ms
instrument.ts:129 useProcess: worker time 834.25ms
instrument.ts:129 useProcess 843.9349999988917ms
process.ts:213 Reduced armor combinations from 11623920 to 1968128
process.ts:345 found 96 stat mixes after processing 1968128 stat combinations in 3065.4649999996764 ms
instrument.ts:129 useProcess: worker time 3110.795000000391ms
instrument.ts:129 useProcess 3121.6100000001024ms
DevTools failed to load SourceMap: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/content_start/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/content/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/vendors/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`
``

### PR DESCRIPTION
**Pull request by ryan-rushton**
Ok so this introduces support for negative stats and moves the optimiser to use the base stat from DimStat over calculating it ourselves in process (now we just add masterwork values if they are there).

I have a bunch of warnings around the place when the stat values may be off which you will see in the following screen shots. The only place I haven't added something and maybe should is in the organiser. I am not quite sure where to put it tbh. It should be evident in the screenshot for that.

Case where we know the stats are right
Screen Shot 2020-07-18 at 4 21 57 pm
Screen Shot 2020-07-18 at 4 22 12 pm

Case where we don't know the stats are wrong (the icon has a title)
Screen Shot 2020-07-18 at 4 22 41 pm
Screen Shot 2020-07-18 at 4 22 50 pm

Class items case as it is handled differently
Screen Shot 2020-07-18 at 4 23 04 pm
Screen Shot 2020-07-18 at 4 23 13 pm

Organiser, note the last row
Screen Shot 2020-07-18 at 4 23 54 pm

Optimiser, note the warning icon next to total (which has a title) and the updated text
Screen Shot 2020-07-18 at 4 20 27 pm

Fixes #5381 
Fixes #4890

### CODE REVIEW

**Comment by ryan-rushton** [comment]
There is one other little change that needs to go in with this but I need #5443 to go in before I can hook it up.

**Comment by ryan-rushton** [comment]
Some updated screenshots of colours and tool tips

Screen Shot 2020-07-18 at 8 35 20 pm
Screen Shot 2020-07-18 at 8 35 34 pm
Screen Shot 2020-07-18 at 8 36 19 pm

File: src/app/inventory/store/stats.ts [hunk 1]
```diff
@@ -505,10 +515,12 @@ export function interpolateStatValue(value: number, statDisplay: DestinyStatDisp
...
 
   // Clamp the value to prevent overfilling
-  value = Math.max(0, Math.min(value, statDisplay.maximumValue));
+  value = Math.min(value, statDisplay.maximumValue);
 
   let endIndex = interp.findIndex((p) => p.value > value);
-  if (endIndex < 0) {
+
+  // value < 0 is for mods with negative stats
+  if (endIndex < 0 || value < 0) {
```
Comment (bhollis) [inline src/app/inventory/store/stats.ts:523]: I'm not sure this is correct - if value < 0, shouldn't we use the first interpolation table entry, not the last?

File: src/app/item-popup/ItemStat.m.scss [hunk 2]
```diff
@@ -83,6 +83,13 @@
   }
 }
 
+.negativeModded {
+  color: #ff3232;
```
Comment (bhollis) [inline src/app/item-popup/ItemStat.m.scss:87]: I *think* we have a red text color defined in `_variables.scss`, but if not we should make one.

File: src/app/loadout-builder/generated-sets/GeneratedSet.tsx [hunk 3]
```diff
@@ -90,11 +91,32 @@ function GeneratedSet({
     ? assignModsToArmorSet(set.firstValidSet, lockedArmor2Mods)
     : {};
 
+  const incorrectStats = _.uniq(
```
Comment (bhollis) [inline src/app/loadout-builder/generated-sets/GeneratedSet.tsx:94]: Might be nice to extract a helper for this?

File: src/app/loadout-builder/hooks/useProcess.ts [hunk 4]
```diff
@@ -219,6 +221,28 @@ function mapSeasonalModsToSeasonsArray(
   return modMetadata;
 }
 
+function getTotalSeasonalModStatChanges(lockedSeasonalMods: readonly LockedModBase[]) {
```
Comment (bhollis) [inline src/app/loadout-builder/hooks/useProcess.ts:224]: Can you document what this does?

File: src/app/item-popup/ItemStat.m.scss (hunk 2 above)
Comment (ryan-rushton) [reply src/app/item-popup/ItemStat.m.scss:87]: We do but it is very hard on the eyes. @sundevour brought up that it might be hard for colorblind people so I made this one. TBH I would be all for changing the default one to make it a little lighter. You can see the difference between the first and last screenshots.

File: src/app/inventory/store/stats.ts (hunk 1 above)
Comment (ryan-rushton) [reply src/app/inventory/store/stats.ts:523]: No because it would 0 cap them and I need that value to remain negative. I believe the table entires for all these stats are 0 and 42. This does line up with what bungie shows for those stats on items, but the mods themselves have negative values, which implies those table values done get used.

File: src/app/loadout-builder/hooks/useProcess.ts (hunk 4 above)
Comment (ryan-rushton) [reply src/app/loadout-builder/hooks/useProcess.ts:224]: Done

File: src/app/loadout-builder/generated-sets/GeneratedSet.tsx (hunk 3 above)
Comment (ryan-rushton) [reply src/app/loadout-builder/generated-sets/GeneratedSet.tsx:94]: I will do the stat display component you mentioned in the top comment and pull this out as part of that.
