### PR TITLE
Include postmaster items in search transfers

### LINKED ISSUE #7400: Unable to transfer items part of a search from Postmaster to Char/Vault
### DIM Version

Version 6.94.0.1000975 (beta), built on 12/8/2021, 1:29:30 PM

### Browser Details

Chrome 96.0.4664.45 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Items found via a search string located in postmaster no longer transfer to vault or character.

eg: is:inpostmaster tag:keep > Send to vault

Results in 
Loadout: Filtered Items
Applying loadout with 0 items to Vault

See attached.

dim

### Logs

```shell
Language Detected: en-gb
instrument.ts:130 Language Assigned: en
fetch.ts:72 POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:72
t @ syncpromise.ts:34
(anonymous) @ fetch.ts:71
t.add @ promisebuffer.ts:34
e._sendRequest @ fetch.ts:69
e.sendSession @ fetch.ts:31
t.sendSession @ basebackend.ts:108
t._sendSession @ baseclient.ts:285
t.captureSession @ baseclient.ts:181
t._sendSessionUpdate @ hub.ts:471
t.captureSession @ hub.ts:411
(anonymous) @ sdk.ts:226
(anonymous) @ sdk.ts:98
Mt @ sdk.ts:18
39515 @ exceptions.ts:125
s @ bootstrap:19
2914 @ main-e61a03.js:1
s @ bootstrap:19
82823 @ main-e61a03.js:1
s @ bootstrap:19
81347 @ main-e61a03.js:1
s @ bootstrap:19
899 @ main-e61a03.js:1
s @ bootstrap:19
9606 @ main-e61a03.js:1
s @ bootstrap:19
(anonymous) @ main-e61a03.js:1
s.O @ chunk loaded:23
(anonymous) @ main-e61a03.js:1
t @ jsonp chunk loading:71
(anonymous) @ main-e61a03.js:1
instrument.ts:130 [dim sync] globalSettings {dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 30, autoRefresh: false, refreshProfileOnVisible: true, …}
instrument.ts:130 [app] DIM v6.94.0.1000975 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
log.ts:44 Load manifest: 1826.2177734375 ms
log.ts:44 Process inventory: 89.407958984375 ms
log.ts:44 Inventory state update: 859.75927734375 ms
instrument.ts:130 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 75.9228515625 ms
log.ts:44 Inventory state update: 95.572998046875 ms
instrument.ts:130 [dim sync] Saving profile data to IDB
log.ts:44 prepareUpdateQueue: 0.251953125 ms
instrument.ts:130 [flushUpdates] Flushing queue of 1 updates
instrument.ts:130 [flushUpdates] got results [{…}] [{…}]
instrument.ts:130 [dim sync] Saving profile data to IDB
instrument.ts:130 [loadout] Apply loadout Filtered Items to Vault
```

### PR DESCRIPTION
**Pull request by bhollis**
Fixes #7400

As far as I can tell search transfers never included postmaster items - or at least not for a very long time. I'm not sure why it was that way, or what would break with this change.

### CODE REVIEW

File: src/app/loadout-drawer/auto-loadouts.ts [hunk 1]
```diff
@@ -187,7 +187,7 @@ export function gatherEngramsLoadout(
  */
 export function itemMoveLoadout(items: DimItem[], store: DimStore): Loadout {
   // Don't move things from the postmaster or that can't move
```
Comment (kyleshay) [inline src/app/loadout-drawer/auto-loadouts.ts:189]:
```suggestion
```

**Review by nev-r — APPROVED** [review]
