### PR TITLE
Fix async process race condition that led to deleted tags

### LINKED ISSUE #6746: Lost tags
Using beta.
Switched between d2 and d1
When switching back lost all tags and all items were new items

### LINKED ISSUE #7282: Lost all tags and notes
### DIM Version

Version 6.91.2.1000858 (beta), built on 11/17/2021, 12:50:19 AM

### Browser Details

Edge 95.0.1020.53

### OS Details

Windows 11

### Describe the bug

I did not check if my tags and notes were available before I checked my D1 items, but when I came back to D2 items, I discovered that all my tags and notes were gone.
I have tried to restart DIM using it as an app from Edge, and I also signed out, then back in, but with no luck :-(
Do you know what can make this happen, so I don't do it again, this is a pain in the bud, as I have a full vault and have marked all my items for keep, favorite, archive and infuse + notes on several items.
All my settings are fine and has not been messed up.

I am a Senior software developer myself, and I don't do silly mistakes, and I am sure I did not do anything for this to happen.

Best regards,
Bill

P.S.: I closed DIM several times after the issue, so the logs are not there anymore, sorry.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by bhollis**
In #7282 I finally figured out a reliable repro for having your tags and notes get deleted:

1. Load your inventory.
2. Open the menu, and hover over a second account.
3. Press R to reload data, then quickly click on the other account.
4. Tags and notes are gone in the second account.

What this was was a race condition, where the first account's data finished loading after we had switched to the second account. Since some of our Redux actions, including the "tag cleanup" action, operated on the state as it is in that instant, rather than the state when the inventory load process was *started*, it would attempt to clean the new account's tag data based on the old account's stores, and would thus consider all items to be deleted.

To address this, I've added strategic early exits from the stores loading process so if the active account has changed from under them, they won't attempt to apply any changes to the global inventory state. ~I've also added a second layer of protection where if we ever attempt to delete all tags, we instead log an exception to Sentry. It's my bad that we didn't have that before - I had thought I had already done that.~ I remember why I didn't do this - if you have only a few tags, and you delete all those items (e.g. you only use tagging to mark junk), it's totally reasonable to delete all tags.

This is in some ways a consequence of poor state design, where we should really have our inventory stored per-account instead of globally - that's a bigger change that I'll defer for later.

Fixes #7282
Fixes #6746

### CODE REVIEW

File: src/app/inventory/StoreBucket.tsx [hunk 1]
```diff
@@ -79,9 +79,14 @@ function mapStateToProps() {
           items = [...items, ...findItemsByBucket(otherStore, bucket.hash)];
         }
       }
-      const currentStore = currentStoreSelector(state)!;
+      const currentStore = currentStoreSelector(state);
+      // TODO: When we switch accounts this suffers from the "zombie child" problem where the redux store has already
+      // updated (so currentStore is cleared) but the store from props is still around because its redux subscription
+      // hasn't fired yet.
```
Comment (bhollis) [inline src/app/inventory/StoreBucket.tsx:85]: This is a separate but somewhat related problem related to how Redux works in general. I'm not super sure how to fix it. For more reading: https://react-redux.js.org/api/hooks#stale-props-and-zombie-children

File: src/app/inventory/d1-stores.ts [hunk 2]
```diff
@@ -26,33 +26,39 @@ import { resetItemIndexGenerator } from './store/item-index';
...
           dispatch(getDefinitions()) as any as Promise<D1ManifestDefinitions>,
           dispatch(loadNewItems(account)),
           getStores(account),
         ]);
+
         const lastPlayedDate = findLastPlayedDate(rawStores);
-        const buckets = bucketsSelector(getState())!;
+        const buckets = d1BucketsSelector(getState())!;
 
-        const stores = await Promise.all(
```
Comment (bhollis) [inline src/app/inventory/d1-stores.ts:48]: This turned out not to have been a promise since some long time ago, but we'd never updated to not treat it as a promise.

File: src/app/inventory/d1-stores.ts [hunk 3]
```diff
@@ -26,33 +26,39 @@ import { resetItemIndexGenerator } from './store/item-index';
...
 
         const [defs, , rawStores] = await Promise.all([
           dispatch(getDefinitions()) as any as Promise<D1ManifestDefinitions>,
           dispatch(loadNewItems(account)),
           getStores(account),
         ]);
+
         const lastPlayedDate = findLastPlayedDate(rawStores);
-        const buckets = bucketsSelector(getState())!;
+        const buckets = d1BucketsSelector(getState())!;
```
Comment (bhollis) [inline src/app/inventory/d1-stores.ts:49]: This incidentally fixes another long standing bug I've seen in Sentry, where the buckets aren't defined. It's because the account could be different here, and `bucketsSelector` depends on `destinyVersionSelector` which depends on `currentAccount`.

File: src/app/inventory/d2-stores.ts [hunk 4]
```diff
@@ -174,13 +179,20 @@ function loadStoresData(
...
+
         const stopTimer = timer('Process inventory');
 
         if (!defs || !profileInfo) {
           return;
         }
 
-        const stores = await buildStores(dispatch, getState, defs, profileInfo, transaction);
+        const buckets = d2BucketsSelector(getState())!;
+        const stores = buildStores(defs, buckets, profileInfo, transaction);
```
Comment (bhollis) [inline src/app/inventory/d2-stores.ts:195]: This wasn't a promise either
