### PR TITLE
Fix energy swap display.

### LINKED ISSUE #7407: LO assigns mods of one element, but displays the item as another element
### DIM Version

Ver6.94.0.1000978(beta)，build：2021/12/8 4:48:22pm

### Browser Details

Microsoft Edge 96.0.1054.43

### OS Details

MacOS 12.0.1

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ryan-rushton**
This fixes the energy swap display issue.

The reason this happened is that we are now returning the initial sockets from the assignment algorithm for the mod swap API. This was an issue here as those plugs have no energy cost. This will be something to keep in mind for future changes.

Screen Shot 2021-12-09 at 10 14 10 pm

Fixes #7407

### CODE REVIEW

File: src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ function EnergySwap({
 
   const modCost = _.sumBy(assignedMods, (mod) => mod.plug.energyCost?.energyCost || 0);
   const modEnergyHashNotAny = assignedMods?.find(
-    (mod) => mod.plug.energyCost?.energyType !== DestinyEnergyType.Any
+    (mod) => mod.plug.energyCost && mod.plug.energyCost.energyType !== DestinyEnergyType.Any
```
Comment (bhollis) [inline src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx:34]: Do we also want to filter out the inevitable manifest data bug where they make an item with "Solar energy cost 0"?

**Review by bhollis — APPROVED** [review]

File: src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx (hunk 1 above)
Comment (ryan-rushton) [reply src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx:34]: Yeah can do, althought if they actually make a mod with an energy type and no energy it may be busted.
