### PR TITLE
Fix being unable to add multiple equipped items to a loadout bucket from the item picker

### LINKED ISSUE #5015: Creating Loadouts issue
Currently when adding new weapons to a loadout I can't see the weapons being added - nothing changes with regards to the slots being take up although when I keep adding weapons it presents the prompt 'limit of 10' as you'd expect so it looks like they're being added.  
I have reinstalled DIM to my phone a few times. I'm using the Galaxy s10+ btw. 

Thanks.

### PR DESCRIPTION
**Pull request by bhollis**
Fixes #5015

### CODE REVIEW

**Comment by bhollis** [comment]
Fixed #5020 too, pretty dumb bug.

File: src/app/loadout/LoadoutDrawer.tsx [hunk 1]
```diff
@@ -90,12 +90,12 @@ function mapStateToProps() {
...
       label: string;
       value: DestinyClass;
-    }[] = [{ label: t('Loadouts.Any'), value: DestinyClass.Unknown }];
-    _.uniqBy(
+    }[] = _.uniqBy(
       stores.filter((s) => !s.isVault),
       (store) => store.classType
     ).map((store) => ({ label: store.className, value: store.classType }));
-    return classTypeValues;
+    console.log();
```
Comment (delphiactual) [inline src/app/loadout/LoadoutDrawer.tsx]: stray
