### PR TITLE
Fix: Select unenhanced perk versions in Armory

### LINKED ISSUE #10910: Wish list rolls should match enhanced versions of perks for enhanceable weapons
### DIM Version

Version 8.56.0 (release), built on 1/26/2025, 8:17:01 PM

### Browser Details

Chrome 131.0.0.0 

### OS Details

Windows 10

### Describe the bug

My Martyr's Retribution perfectly matches my wishlist except that I've enhanced the weapon and its perks, so DIM's armory window (i think thats what its called) shows it as not having 3rd/4th column perks, and not matching any rolls

Image

The only place it shows the thumbs up is on the Triage button on the popup, but my main issue is with it not autofilling perks into armory

Image

small bug ik, but i feel like its worth reporting

### Logs

```shell

```

### PR DESCRIPTION
**Pull request by chainrez**
Fixes #10910

DIM doesn't show enhanced perks at all in the Armory for Enhanceable weapons, but they are there in the PlugSet, marked currentlyCanRoll=false (see [https://data.destinysets.com/i/InventoryItem:1762785663/PlugSet:3559076750](https://data.destinysets.com/i/InventoryItem:1762785663/PlugSet:3559076750))

This causes plug overrides to fail, causing the fake item in Armory to have no perks highlighted, causing no perks to be highlighted in visualized Sishlist entries below.

Simple fix here converts selected perks to un-enhanced, so they will match Wishlists and generate a more normal looking Armory entry. Several followup issues should be addressed here: https://github.com/DestinyItemManager/DIM/issues/11040

### CODE REVIEW

File: src/app/inventory/store/override-sockets.ts [hunk 1]
```diff
@@ -46,7 +47,9 @@ export function applySocketOverrides(
       let newPlug, actuallyPlugged;
 
       if (s.isPerk) {
-        newPlug = plugOptions.find((p) => p.plugDef.hash === override);
+        newPlug = plugOptions.find(
```
Comment (bhollis) [inline src/app/inventory/store/override-sockets.ts:50]: It might be better to do two scans, so that if there exists an enhanced plug, you'll use it, and only fall back to the regular plug if it's not found.

Comment (chainrez) [reply src/app/inventory/store/override-sockets.ts:50]: Great point and very relevant for Crafted weapon column ordering. Fixed, thanks.
