### PR TITLE
Fix error when applying consumables from a (search) loadout

### LINKED ISSUE #7602: Bulk moving inventory items doesn't always work consistently
### DIM Version

6.97.1.1001102 (beta)

### Browser Details

Chrome 96.0.4664.110

### OS Details

openSUSE Leap 15.3

### Describe the bug

I've got the following query:

`is:movable -is:armor -is:weapon -is:ships -is:vehicle -is:ghost -name:"mod components" -name:"sweaty confetti"`

Until recently, I could select the three-dot menu at the end of the search bar and select "move to vault", and the items would move without any issue.  Recently, though, this stopped working consistently - if I move items from the vault into the character inventory and then use this query, they move OK.  If I just have been playing the game and they are collected during gameplay, one item moves at a time for each attempt to move the selected items.

### Logs

```shell
[loadout] Apply loadout Filtered Items to Vault
instrument.ts:130 [move] Move 1 Pure Matterglass Lens Consumables to Vault from Exo Warlock
instrument.ts:130 [loadout] Failed to apply loadout item Pure Matterglass Lens TypeError: Cannot set properties of undefined (setting 'state')
    at loadout-apply.ts:363
    at immerClass.ts:78
    at e.produce (immerClass.ts:94)
    at immerClass.ts:78
    at loadout-apply-state.ts:142
    at loadout-apply.ts:361
(anonymous) @ instrument.ts:130
s @ log.ts:33
(anonymous) @ loadout-apply.ts:378
await in (anonymous) (async)
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:107
(anonymous) @ action-queue.ts:13
Promise.then (async)
o @ action-queue.ts:12
(anonymous) @ loadout-apply.ts:106
(anonymous) @ index.js:16
(anonymous) @ ItemActionsDropdown.tsx:85
onSelected @ ItemActionsDropdown.tsx:99
(anonymous) @ downshift.esm.js:118
(anonymous) @ downshift.esm.js:116
Be @ react-dom.production.min.js:52
qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Tr @ react-dom.production.min.js:100
Pr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
(anonymous) @ scheduler.production.min.js:18
$o @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Gt @ react-dom.production.min.js:73
r @ helpers.ts:88
instrument.ts:130 [loadout] failed loadout {phase: 2, equipNotPossible: false, itemStates: {…}, socketOverrideStates: {…}, modStates: Array(0)} TypeError: Cannot set properties of undefined (setting 'state')
    at loadout-apply.ts:383
    at immerClass.ts:78
    at e.produce (immerClass.ts:94)
    at immerClass.ts:78
    at loadout-apply-state.ts:142
    at loadout-apply.ts:379
(anonymous) @ instrument.ts:130
s @ log.ts:33
(anonymous) @ loadout-apply.ts:127
await in (anonymous) (async)
(anonymous) @ index.js:16
(anonymous) @ ItemActionsDropdown.tsx:85
onSelected @ ItemActionsDropdown.tsx:99
(anonymous) @ downshift.esm.js:118
(anonymous) @ downshift.esm.js:116
Be @ react-dom.production.min.js:52
qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Tr @ react-dom.production.min.js:100
Pr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
(anonymous) @ scheduler.production.min.js:18
$o @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Gt @ react-dom.production.min.js:73
r @ helpers.ts:88
log.ts:44 Loadout Application: 1216.26416015625 ms
```

### PR DESCRIPTION
**Pull request by bhollis**
Fixes #7602

### CODE REVIEW

File: src/app/inventory/item-move-service.ts [hunk 1]
```diff
@@ -566,7 +566,7 @@ function chooseMoveAsideItem(
     throw new DimError(
       'no-space',
       t('ItemService.NotEnoughRoom', { store: target.name, itemname: item.name })
-    );
+    ).withError(new DimError('ItemService.NotEnoughRoomGeneral'));
```
Comment (ryan-rushton) [inline src/app/inventory/item-move-service.ts:569]: Why not just have a distinct error that represents these two things? Triggering a "cause" error makes more sense to me if it was thrown from somewhere else and caught here.

**Review by ryan-rushton — APPROVED** [review]

File: src/app/inventory/item-move-service.ts (hunk 1 above)
Comment (bhollis) [reply src/app/inventory/item-move-service.ts:569]: Take a look at how the error grouping works - the error specifically calls out the item, but the errors need something to be grouped on, and I used the cause as a grouping key. LMK if you have a better idea.
