### PR TITLE
Closable mods fix for #5341

### LINKED ISSUE #5341: Mods in Loadout Optimizer mod picker have close buttons
Mods in the mod picker have a "close" button that doesn't do anything:
image

### PR DESCRIPTION
**Pull request by ryan-rushton**
Gave CloseableContainer an enabled prop so we can show the close button selectively for removable mods.

Fixes #5341 

image

### CODE REVIEW

File: src/app/loadout-builder/ClosableContainer.tsx [hunk 1]
```diff
@@ -6,15 +6,17 @@ import styles from './ClosableContainer.m.scss';
  */
 export default function ClosableContainer({
   children,
+  enabled,
```
Comment (bhollis) [inline src/app/loadout-builder/ClosableContainer.tsx:9]: You could default this to true.

Comment (ryan-rushton) [reply src/app/loadout-builder/ClosableContainer.tsx]: Done, I never normally use default props but I don't mind it here I suppose.
