### PR TITLE
Fix tooltip text, while still hiding it for enhanceable weapons' tooltips

### LINKED ISSUE #10594: Display Hammer Charges
image

### PR DESCRIPTION
**Pull request by FlaminSarge**
Fixes #10594 

Wondering if `!isDeepsightTooltip` ever functioned here or always blocked this from displaying.

I unfortunately don't think I have any items that fulfill the expiration or deepsight cases to check on those.

Screenshot 2024-08-01 at 8 33 42 PM

### CODE REVIEW

**Comment by FlaminSarge** [comment]
I was debating moving it to the stack count UI but that'd require parsing the tooltip to figure that out which seems not-ideal.

File: src/app/dim-ui/DestinyTooltipText.tsx [hunk 1]
```diff
@@ -11,8 +12,9 @@ export function DestinyTooltipText({ item }: { item: DimItem }) {
   }
   return (
     <>
-      {!isDeepsightTooltip &&
```
Comment (bhollis) [inline src/app/dim-ui/DestinyTooltipText.tsx:14]: Yeah that's a whoops, since it didn't actually *call* the function. I had hoped our linter would catch this sort of thing.

**Review by bhollis — APPROVED** [review]
We should maybe do a once-over and see if any of the other tooltips are valuable now.

File: src/app/dim-ui/DestinyTooltipText.tsx (hunk 1 above)
Comment (robojumper) [reply src/app/dim-ui/DestinyTooltipText.tsx:14]: Yeah I ran into the same problem already once. There's an open suggestion on the TS repo https://github.com/microsoft/TypeScript/issues/45667
