### PR TITLE
Loadout live notify

### LINKED ISSUE #7369: Live loadout apply status
Right now we show a notification that just says "applying N items" and swap that display if anything changes. Instead I'd like to render a "live" react component as the notification body which subscribes to an Observable of the current status and updates with how far it's gotten, any errors, what it's doing now, etc.

### LINKED ISSUE #7374: Handle errors while applying a loadout better
We should:

1. Be better about when we stop applying a loadout due to an error and when we don't. For example, if we fail to equip, we might still want to make sure everything is moved, and apply mods to the items that *would've* been equipped.
2. Short-circuit equips and mod changes more decisively when we get the error that the user is in an activity and equipping is not allowed.

### PR DESCRIPTION
**Pull request by bhollis**
Screen Shot 2021-12-22 at 5 18 22 PM
Screen Shot 2021-12-22 at 5 18 33 PM

This hooks up live status for loadout application to the notification, so you can see as each item and mod does its thing. There's detailed statuses and errors for each one. Plus:

1. A top level property for when we detect you can't equip because you're in an activity, so we can show something consolidated and nice. Theoretically this could be used to short-circuit a lot of actions but I haven't wired that up yet.
2. Revamped error handling across all loadout actions so we will stubbornly attempt to apply as much of the loadout as we can, rather than failing at the first sign of errors.
3. Applying mods will apply to the items marked "equipped" from the loadout even if they didn't get equipped, rather than applying to whatever's currently equipped.
4. Made the function for moving a loadout item not be recursive anymore (not sure why it ever was), and got it set up to be done in parallel though I'll leave it to a separate change to actually run it in parallel. Could speed things up a bit.
5. Always set farming mode back on even if things fail.
5. Fixed a couple bugs!

Folks will have to tell me if we need an "in progress state" with a spinner or pulsing opacity for the items/mods that are currently being applied, or if it's OK to just have them pop in when they reach terminal state.

The loadout apply function is pretty huge - I want to move these files to another folder and factor out some big chunks, but for readability of the diff I left them in place for now.

Fixes #7369
Fixes #7374

### CODE REVIEW

File: src/app/loadout-drawer/loadout-apply.ts [hunk 1]
```diff
@@ -798,73 +976,90 @@ function applyLoadoutMods(
...
-        if (includeAssignToDefault || !isAssigningToDefault(item, { socketIndex, mod }, defs)) {
-          successfulMods.push(mod.hash);
+        if (includeAssignToDefault || !isAssigningToDefault(item, assignment, defs)) {
+          onSuccess(assignment);
         }
         continue;
       }
-      const defaultPlugHash = getDefaultPlugHash(socket, defs);
-      if (defaultPlugHash && canInsertPlug(socket, defaultPlugHash, destiny2CoreSettings, defs)) {
+      if (canInsertPlug(socket, mod.hash, destiny2CoreSettings, defs)) {
```
Comment (bhollis) [inline src/app/loadout-drawer/loadout-apply.ts:1062]: Pretty sure this was a bug? I'm not sure why we were checking whether we can insert the default plug instead of the actual plug.

File: src/app/loadout-drawer/loadout-apply.ts [hunk 2]
```diff
@@ -96,423 +98,534 @@ export function applyLoadout(
...
-    if (itemsToEquip.length > 1) {
-      // we'll use the equipItems function
-      itemsToEquip.forEach((i) => {
-        i.equipped = false;
+          return notAlreadyThere;
+        }),
+        // Shallow copy all LoadoutItems so we can mutate the equipped flag later
+        (i) => ({
+          ...i,
+        })
```
Comment (nev-r) [inline src/app/loadout-drawer/loadout-apply.ts:266]:
```suggestion
        (i) => ({ ...i })
```

File: src/app/loadout-drawer/loadout-apply.ts [hunk 3]
```diff
@@ -96,423 +98,534 @@ export function applyLoadout(
...
+              // Items in the postmaster should be moved even if they're on the same character
+              item.location.inPostmaster ||
+              // Needs to be equipped. Stuff not marked "equip" doesn't
+              // necessarily mean to de-equip it.
+              (loadoutItem.equipped && !item.equipped) ||
+              // We always try to move consumable stacks because their logic is complicated
+              (loadoutItem.amount && loadoutItem.amount > 1));
+
+          // TODO: hate the double negative
+          if (item && !notAlreadyThere) {
```
Comment (nev-r) [inline src/app/loadout-drawer/loadout-apply.ts:253]:
```suggestion
          if (item && !requiresAction) {
```

File: src/app/loadout-drawer/loadout-apply.ts [hunk 4]
```diff
@@ -96,423 +98,534 @@ export function applyLoadout(
...
+            );
+          }
 
-    // We'll equip these all in one go!
-    let itemsToEquip = loadoutItemsToMove.filter((i) => i.equipped);
-    if (itemsToEquip.length > 1) {
-      // we'll use the equipItems function
-      itemsToEquip.forEach((i) => {
-        i.equipped = false;
+          return notAlreadyThere;
```
Comment (nev-r) [inline src/app/loadout-drawer/loadout-apply.ts:261]:
```suggestion
          return requiresAction;
```

File: src/app/loadout-drawer/loadout-apply.ts [hunk 5]
```diff
@@ -96,423 +98,534 @@ export function applyLoadout(
...
-      loadoutItemsToMove.forEach((i) => {
-        i.equipped = false;
-      });
-    }
+      // Filter out items that don't need to move
+      const loadoutItemsToMove: LoadoutItem[] = Array.from(
+        applicableLoadoutItems.filter((loadoutItem) => {
+          const item = getLoadoutItem(loadoutItem, store, getStores());
+          // Ignore any items that are already in the correct state
+          const notAlreadyThere =
```
Comment (nev-r) [inline src/app/loadout-drawer/loadout-apply.ts:240]:
```suggestion
          const requiresAction =
```

File: src/app/inventory/item-move-service.ts [hunk 6]
```diff
@@ -223,15 +223,18 @@ function searchForSimilarItem(
 }
 
 /**
- * Bulk equip items. Only use for multiple equips at once.
+ * Bulk equip items. Only use for multiple equips at once (just loadouts).
+ * Returns a list of items that were successfully equipped, which can be less
```
Comment (ryan-rushton) [inline src/app/inventory/item-move-service.ts:227]:
```suggestion
 * Returns a map of items id's to their success status (PlatformErrorCodes.Success if it succeeded), which can be less
```

Comment (ryan-rushton) [reply src/app/inventory/item-move-service.ts:227]: `PlatformErrorCodes` is an odd name for an enum that can contain a `success` state.

**Review by ryan-rushton — APPROVED** [review]
Working nicely for me and a drastic improvement in UI

**Review by nev-r — APPROVED** [review]
