### PR TITLE
Fix dialog symbols picker

### LINKED ISSUE #9769: input/textarea hashtag/symbols autocomplete dropdown no longer appears
### DIM Version

Version 7.82.1.1002836 (beta), built on 24/08/2023, 8:18:30 pm

### Browser Details

Firefox 117.0

### OS Details

Windows 10

### Describe the bug

Suspect it's caused by #9765 as this was working prior to that change, but typing a colon no longer shows the symbol popup sheet in Firefox.

Opening in Chrome still works, however.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by robojumper**

### CODE REVIEW

File: src/app/dim-ui/destiny-symbols/SymbolsPicker.tsx [hunk 1]
```diff
@@ -150,15 +161,15 @@ function SymbolsPickerButton<T extends HTMLTextAreaElement | HTMLInputElement>({
...
+          <div ref={tooltipContents}>
             <ClickOutside onClickOutside={() => setOpen(false)}>
               <SymbolsWindow onChooseGlyph={onChooseGlyph} />
             </ClickOutside>
-          </div>
-        </Portal>
-      )}
+          </div>,
+          pressTipRoot.current ?? tempContainer
+        )}
```
Comment (robojumper) [inline src/app/dim-ui/destiny-symbols/SymbolsPicker.tsx:172]: This is a revert of an earlier change that fixed non-interactivity for the item popup symbols picker, but it broke the dialog symbols picker. The `pointer-events: auto;` change above fixes this in a different way.

**Review by bhollis — APPROVED** [review]

**Review by bhollis — APPROVED** [review]
