### PR TITLE
Raid mod assignment fix

### LINKED ISSUE #6679: Mod assignment algorithm breaking for raid mods.
When locking a void class item, for some reason I cannot get results with a raid mod locked even though I have an item available to slot into it. I first noticed this when locking a full suite of mods, as there was obviously room to use the correct mod. This doesn't seem to be an issue with arc or solar class items.

image

image

### PR DESCRIPTION
**Pull request by ryan-rushton**
Fixed issue where raid mods were not being assigned correctly.
Also optimised a little earlier by counting raid mod element types.

Fixes #6679

### CODE REVIEW

File: src/app/loadout-builder/process-worker/process-utils.ts [hunk 1]
```diff
@@ -220,18 +244,20 @@ export function canTakeSlotIndependantMods(
...
-                item.compatibleModSeasons?.includes(raidTag))
+            raidEnergyIsValid &&
+              notLegacySocketOrLegacyMod &&
+              raidTag &&
+              item.compatibleModSeasons?.includes(raidTag)
           );
-        }
 
-        if (!raidsFit) {
-          break;
```
Comment (ryan-rushton) [inline src/app/loadout-builder/process-worker/process-utils.ts:232]: This was the issue I believe, it was breaking the "mods" loop and not checking other permutations.

**Review by nev-r — APPROVED** [review]

**Comment by nev-r** [comment]
definitely enabling raid mod builds that came up 0
