### PR TITLE
Remember LO stat constraints per class

### LINKED ISSUE #7572: Opening a shared loadout overwrites your LO stat preferences.
### DIM Version

all versions

### Browser Details

Firefox Current

### OS Details

windows 10

### Describe the bug

when you click someone's shared loadout link, LO loads up with that build preferred stats. but from then on when you go into LO those preferences are saved as default till you change them back to your preferred. 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by robojumper**
dim-api settings had a property for that already and it seemed useful. Tried to do some cleanup with how we initialize a loadout optimizer session.

Also should fix #7572.

### CODE REVIEW

**Comment by robojumper** [comment]
For some reason hitting F5 reverts to the default in-game stat order, so I need to take care of that still.

File: src/app/loadout-builder/LoadoutBuilderContainer.tsx [hunk 1]
```diff
@@ -87,9 +99,7 @@ export default function LoadoutBuilderContainer({ account }: Props) {
       account={account}
       stores={stores}
       preloadedLoadout={preloadedLoadout}
-      initialClassType={urlClassType}
-      notes={urlNotes ?? preloadedLoadout?.notes}
-      initialLoadoutParameters={urlLoadoutParameters || savedLoadoutParameters}
+      urlParameters={urlParameters}
```
Comment (bhollis) [inline src/app/loadout-builder/LoadoutBuilderContainer.tsx:102]: The only thing about switching to an object here is that the `memo` in `LoadoutBuilder` won't work anymore.

**Review by bhollis — APPROVED** [review]

File: src/app/loadout-builder/LoadoutBuilderContainer.tsx (hunk 1 above)
Comment (robojumper) [reply src/app/loadout-builder/LoadoutBuilderContainer.tsx]: I changed that part back because it honestly didn't make things much clearer.
