### PR TITLE
Fix bounty and armor ownership display in vendors page

### LINKED ISSUE #7594: Available bounties incorrect over multiple characters
If I purchase a bounty on one character it will show as purchased on all 3 from the vendor view. This only started happening in the last few months, and is happening on desktop (chrome) and android. I've attached some screen shots to explain it better.

From the D2 app you can see I have purchased the daily crucible bounties on my hunter but not on my warlock.
image
image
But within DIM they show as purchased on both accounts.
image
image

If I complete the bounty on my hunter it then correctly shows as completed (not just purchased) on my hunter, and available on my warlock.

Let me know if I can provide any more detail.

### LINKED ISSUE #7597: Vendors page incorrectly shows some collections armor as being owned
### DIM Version

Version 6.97.1.1001100 (beta), built on 29.12.2021, 21:57:09

### Browser Details

Firefox 95.0.2

### OS Details

Windows 10

### Describe the bug

I don't have any armor pieces from the core playlist vendors in my inventory (I have them in collections though), but the Vendors page claims "This item is in your inventory." for all Vanguard, Crucible and Gambit armor.

The reason is that the selector that builds a set of all owned items checks all plugs for items too so that mods can be shown as acquired:

https://github.com/DestinyItemManager/DIM/blob/8dbed94e2bdc70f6f9da96a5040e47f6036f6298/src/app/inventory/selectors.ts#L109-L129

But, legendary armor pieces report all other legendary pieces as plugs in the universal ornament socket, and the plug options here are those armor pieces (same definition hash). So because those armor pieces double-function as ornament options, DIM considers them valid mods and hence owned.

A fix for #7561 *could* mitigate this, but even then items would wrongly show as owned when they're unlocked as universal ornaments.

Note that some world armor sets with different versions do not suffer from this, as the ornament version is a different item hash from the one currently being offered by vendors (both are proper armor item defs though). There might be a connection to #7023 here.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #7594, fixes #7597.

### CODE REVIEW

File: src/app/inventory/selectors.ts [hunk 1]
```diff
@@ -106,25 +109,83 @@ export const materialsSelector = (state: RootState) =>
...
+            // so without this universal ornaments cause the corresponding armor items
+            // as being owned.
+            return;
+          }
+          const plugSetDef = defs.PlugSet.get(hash);
+          for (const item of plugSetDef.reusablePlugItems) {
+            const itemDef = defs.InventoryItem.get(item.plugItemHash);
+            if (plugs.some((k) => k.plugItemHash === itemDef.hash && k.enabled)) {
+              insertInto.add(itemDef.hash);
+            }
```
Comment (robojumper) [inline src/app/inventory/selectors.ts:167]: I moved this code from `Vendors.tsx` but am not sure what it's trying to accomplish:

1. Why is it requesting the item from defs? Shouldn't `defs.InventoryItem.get(x).hash === x`?
2. Why is it looking at the PlugSet? Is there a case where the profile response lists plugs not present in the PlugSet that must be removed?

File: src/app/inventory/selectors.ts [hunk 2]
```diff
@@ -106,25 +109,83 @@ export const materialsSelector = (state: RootState) =>
...
+      ) => {
+        const items = new Set<number>();
+        _.forIn(plugs, (plugs, plugSetHash) => {
+          const hash = parseInt(plugSetHash, 10);
+          if (universalOrnamentPlugSetHashes.includes(hash)) {
+            // #7597: Plugs from the universal ornament sets are exactly the armor items,
+            // so without this universal ornaments cause the corresponding armor items
+            // as being owned.
+            return;
+          }
```
Comment (robojumper) [inline src/app/inventory/selectors.ts:161]: This might break for universal ornaments for sale in Eververse.

File: src/app/inventory/selectors.ts (hunk 1 above)
Comment (delphiactual) [reply src/app/inventory/selectors.ts:167]: https://github.com/DestinyItemManager/DIM/pull/4449

Comment (bhollis) [reply src/app/inventory/selectors.ts:167]: Yeah that doesn't make a ton of sense to me either. I suspect it was leftover from when I was logging the whole item to try and understand it.

File: src/app/inventory/selectors.ts [hunk 3]
```diff
@@ -106,25 +109,83 @@ export const materialsSelector = (state: RootState) =>
...
+];
+
+/**
+ * For most items, ownership is simple -- if it's in any bucket, we own this item.
+ * For items in some buckets (like quests and emblems), there is no concept of
+ * account-wide ownership. This mostly affects vendor claimability.
+ */
+export interface OwnedItems {
+  accountWideOwned: Set<number>;
+  storeSpecificOwned: Map<string, Set<number>>;
```
Comment (bhollis) [inline src/app/inventory/selectors.ts:127]: In general I prefer a "plain object" whenever the key is a string - I don't think Map adds a lot in that case and it is much harder to work with (can't use spread operator, etc).

File: src/app/inventory/selectors.ts (hunk 2 above)
Comment (bhollis) [reply src/app/inventory/selectors.ts:161]: Possibly you'd need a third set, which is "universal ornaments owned" - we could consult it only when checking an item when it's being treated as a mod, though I don't know how to identify that.

File: src/app/inventory/selectors.ts (hunk 1 above)
Comment (bhollis) [reply src/app/inventory/selectors.ts:167]: I also agree, there doesn't seem to be a need to re-load the PlugSet.

File: src/app/inventory/selectors.ts [hunk 4]
```diff
@@ -106,25 +109,83 @@ export const materialsSelector = (state: RootState) =>
...
+  // Quests and bounties are character-specific.
+  BucketHashes.Quests,
+];
+
+/**
+ * For most items, ownership is simple -- if it's in any bucket, we own this item.
+ * For items in some buckets (like quests and emblems), there is no concept of
+ * account-wide ownership. This mostly affects vendor claimability.
+ */
+export interface OwnedItems {
```
Comment (bhollis) [inline src/app/inventory/selectors.ts:125]: We were less clear about what "ownership" meant at this point - it's worth clarifying that this is ownership as in "Has the item in inventory" vs maybe "unlocked" meaning that you have it in collections.

**Review by bhollis — COMMENTED** [review]
Nice, I like the clearer structure for this.

**Comment by robojumper** [comment]
I've updated this PR with a different approach based on the realization that we're only checking the plugs in the profile response to work around issues where the plug items aren't linked to collectibles. There's no point in using plugs for `records/` since Records specifically shows collectibles and already has special-casing for Plug-collections.

File: src/app/vendors/VendorItemComponent.tsx [hunk 5]
```diff
@@ -46,19 +46,22 @@ export default function VendorItemComponent({
...
+  const mod = item.item.itemCategoryHashes.includes(ItemCategoryHashes.Mods_Mod);
+
+  const unavailable = !item.canPurchase || !item.canBeSold || (owned && ownershipRule);
   return (
     <VendorItemDisplay
       item={item.item}
       unavailable={unavailable}
       owned={owned}
       acquired={acquired}
-      extraData={{ failureStrings: item.failureStrings, owned, acquired }}
```
Comment (robojumper) [inline src/app/vendors/VendorItemComponent.tsx:61]: The `mod` part was from when mods were actual consumables and there was value in showing that a mod was present on some piece of gear. That code has bitrotted since then and `mod` was never set. The change isn't *great* either because it calls shaders "items" but ornaments and emotes "mods", so I'll file an issue to add accurate display names.

File: src/app/inventory/selectors.ts [hunk 6]
```diff
@@ -106,25 +109,97 @@ export const materialsSelector = (state: RootState) =>
...
+ */
+export const ownedItemsSelector = createSelector(allItemsSelector, (allItems) => {
+  const accountWideOwned = new Set<number>();
+  const storeSpecificOwned = {};
+  for (const item of allItems) {
+    if (STORE_SPECIFIC_OWNERSHIP_BUCKETS.includes(item.bucket.hash)) {
+      if (!storeSpecificOwned[item.owner]) {
+        storeSpecificOwned[item.owner] = new Set();
+      }
+      storeSpecificOwned[item.owner].add(item.hash);
```
Comment (bhollis) [inline src/app/inventory/selectors.ts:149]: Potentially distasteful from a readability perspective, but:
```suggestion
      (storeSpecificOwned[item.owner] ??= new Set()).add(item.hash);
```

File: src/app/inventory/selectors.ts [hunk 7]
```diff
@@ -106,25 +109,97 @@ export const materialsSelector = (state: RootState) =>
...
+});
+
+/**
+ * Sets containing all the hashes of owned uncollectible plug items,
+ * e.g. emotes and ghost projections. These plug items do not appear
+ * in collections, so we use plug availability from the profile response
+ * to mark them as "owned". Plugs where the associated item has a
+ * collectibleHash will never be included.
+ */
+export const ownedUncollectiblePlugsSelector = createSelector(
```
Comment (bhollis) [inline src/app/inventory/selectors.ts:165]: Nice. Took me a minute to understand what this meant, but I like how it's defined.

File: src/app/vendors/VendorItemComponent.tsx (hunk 5 above)
Comment (bhollis) [reply src/app/vendors/VendorItemComponent.tsx:61]: Sounds great. I'd love to get rid of this "extraData" thing.

**Review by bhollis — APPROVED** [review]
Fantastic!
