### PR TITLE
Fixed display of energy changes.

### LINKED ISSUE #6993: LO not always showing energy increases
### DIM Version

Version 6.80.0.1000666 (beta), built on 9/2/2021, 1:30:03 AM

### Browser Details

Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

LO isn't showing all armors that need an energy increase, it shows some that stay the same, some that need an affinity swap, but not just general energy increases. 

image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ryan-rushton**
This fixes the janky display of energy swaps when adding mods.

Fixes #6993 

Screen Shot 2021-09-05 at 11 14 14 am

Screen Shot 2021-09-05 at 11 19 01 am

Screen Shot 2021-09-05 at 11 17 32 am

### CODE REVIEW

File: src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx [hunk 1]
```diff
@@ -20,42 +20,50 @@ import Sockets from './Sockets';
...
+  const modEnergyHash = assignedMods?.find(
     (mod) => mod.plug.energyCost?.energyType !== DestinyEnergyType.Any
   )?.plug.energyCost?.energyTypeHash;
   const modEnergy = (modEnergyHash && defs.EnergyType.get(modEnergyHash)) || null;
-  const resultingEnergyCapacity =
-    modEnergy && armorEnergy.hash === modEnergy.hash
-      ? Math.max(itemEnergyCapacity, modCost)
-      : modCost;
+
+  const resultingEnergy = modEnergy ? modEnergy : armorEnergy;
```
Comment (bhollis) [inline src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx:39]:
```suggestion
  const resultingEnergy = modEnergy ?? armorEnergy;
```

**Review by bhollis — APPROVED** [review]
