### PR TITLE
Fix Leviathan's Breath catalyst progress

### LINKED ISSUE #9060: Leviathan's Breath not showing up as having a catalyst
### DIM Version

Version 7.55.0.1002256 (beta), built on 2/5/2023, 7:21:42 PM

### Browser Details

Chrome 109.0.0.0

### OS Details

Windows 10

### Describe the bug

When running `catalyst:incomplete`, my Leviathin's Breath was greyed out.  I noticed then that it doesn't show as having a catalyst slot

### Logs

_No response_

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #9060.

### CODE REVIEW

File: src/app/inventory/store/catalyst.ts [hunk 1]
```diff
@@ -1,18 +1,30 @@
...
 
   const recordHash = exoticToCatalystRecordHash[itemHash];
-  const record = recordHash && profileRecords?.records[recordHash];
+  const record =
+    recordHash &&
+    (profileRecords?.records[recordHash] ??
+      (characterRecords &&
+        _.compact(
+          Object.values(characterRecords).map((records) => records.records[recordHash])
+        )[0]));
```
Comment (bhollis) [inline src/app/inventory/store/catalyst.ts:27]: I *think* this is a bit more efficient? I suppose most cases will hit the `profileRecords` branch though, so maybe it doesn't matter.

```suggestion
        Object.values(characterRecords).find((records) => records.records[recordHash])?.records[recordHash]));
```

**Review by bhollis — APPROVED** [review]
