### PR TITLE
adept compare to non-adept

### LINKED ISSUE #6649: Comparing a non-adept weapon should also compare the adept version
**What version of DIM are you using?**
Version 6.59.1.1000358 (beta), built on 4/5/2021, 6:54:25 AM

**What Browser and OS are you using?**
Chrome on MacOS

**Describe the bug and how to make it happen**
If you compare one of the non-adept weapons that have adept versions (Palindrome, SWARM, Shadow Price), it also pulls in the adept version in the comparison, which is nice.  However, if you do the same compare starting with the adept version of the weapon, it does not pull in the non-adept versions.

I would prefer that it pulls in both adept and non-adept versions if you start the comparison from either version.

### PR DESCRIPTION
**Pull request by delphiactual**
Closes #6649

### CODE REVIEW

**Comment by delphiactual** [comment]
@nev-r I do not have any adept weapons to test this behavior, please assist!

File: src/app/compare/compare-buttons.tsx [hunk 1]
```diff
@@ -110,6 +110,8 @@ const getRpm = (i: DimItem) => {
 export function findSimilarWeapons(exampleItem: DimItem): CompareButton[] {
   const intrinsic = getWeaponArchetype(exampleItem);
   const intrinsicName = intrinsic?.displayProperties.name || t('Compare.Archetype');
+  const isAdept = exampleItem.name.includes(t('Filter.Adept'));
+  const nonAdeptVersion = isAdept ? exampleItem.name.replace(t('Filter.Adept'), '').trim() : null;
```
Comment (bhollis) [inline src/app/compare/compare-buttons.tsx:114]: You can just always remove the adept suffix, whether it's there or not.

**Review by bhollis — APPROVED** [review]
