### PR TITLE
Show selected Super icon on V3 subclasses

### LINKED ISSUE #8045: Bring back selected super display?
The new subclass reworks mean our custom super display doesn't work anymore:
image

Should we:
1. Show the selected super for mod-style subclasses
2. Leave it as is and when they get upgraded they show the generic subclass icon
3. Remove the selected super for non-upgraded subclasses

cc @vivekhnz

### PR DESCRIPTION
**Pull request by vivekhnz**
This PR closes #8045 .
dim-subclass-v3-super-icons

Notable changes:
- Stasis and Void 3.0 subclasses will display their selected super icon instead of the damage type icon.
  - This applies everywhere except the 'locked' subclass selection in Loadout Optimizer
- Arc, Solar and Void subclass base images have been refreshed to look closer to their post-Beyond Light icons (e.g. Arc color was made lighter to be more distinct from Stasis)
- Mapping between V2 to V3 subclasses has moved from `loadout-utils.ts` to `subclass.ts`
  - The reasoning is to try keep all manually curated subclass info in one place

### CODE REVIEW

File: src/app/inventory/ConnectedInventoryItem.tsx [hunk 1]
```diff
@@ -16,6 +16,7 @@ interface ProvidedProps {
   id?: string; // defaults to item.index - id is typically used for `itemPop`
   allowFilter?: boolean;
   ignoreSelectedPerks?: boolean;
+  ignoreSelectedMods?: boolean;
```
Comment (bhollis) [inline src/app/inventory/ConnectedInventoryItem.tsx:19]: I was thinking of replacing both of these with a "showSelectedSubclass" property because that's all it's really used for.

**Review by bhollis — APPROVED** [review]
Nice, I'm super into it. I think it looks really cool.

File: src/app/inventory/ConnectedInventoryItem.tsx (hunk 1 above)
Comment (vivekhnz) [reply src/app/inventory/ConnectedInventoryItem.tsx:19]: Yep, I'm not opposed to that. The complexity is that there are cases where we do want to show selected super for V3 subclasses but not for V2 subclasses (because we DIM can change the Super on V3 subclasses but not V2 subclasses). 

Maybe I should collapse those 2 booleans into a single enum value since there are only 3 valid options? e.g.
`selectedSuperDisplay: 'enabled' | 'disabled' | 'v3SubclassesOnly'`

**Comment by vivekhnz** [comment]
I'm split on whether we should show the selected Super in the loadout drawer + loadouts page. On one hand, it shows you what your configured subclass will look like elsewhere in DIM. On the other hand, the selected Super ability is displayed right next to it so it's possibly redundant.

dim-subclass-v3-super-icons-loadouts

**Comment by bhollis** [comment]
Right, that's the dilemma I'd had as well. I think it's *cooler* in the subclass icon but it's a bit weird to have it duplicated.

**Comment by delphiactual** [comment]
filter it out of the square icons on the loadout page?

**Comment by bhollis** [comment]
@vivekhnz anything else you want to do with this before merging?

**Comment by vivekhnz** [comment]
Sorry, busy week. I'd like to disable the selected super display in the loadout drawer + loadouts page and then it should be good to merge. After thinking through it a bit more, I think it's redundant to show the Super icon twice and showing it on the Super itself is preferable as there's a tooltip describing the ability. I'll try get that done in the next day or so.
