### PR TITLE
Fix well rested showing more xp than it actually requires

### LINKED ISSUE #11379: XP above rank 100 is higher
DIM thinks that Well Rested is exhausted after 2.5kk XP, but it is actually after 500k. I assume it is because DIM calculates XP as xp_per_rank * 5, but because I am above 100 rank, xp_per_rank is 500k, not 100k.

### PR DESCRIPTION
**Pull request by JAssertz**
Changelog: Fixes well rested XP counter from counting ranks 101-110 as 1 level instead of 5

Resolves #11379 

Logic: currently we have a static value of 5 for levels required, this results though in when above 100 counting levels 101-110 each as 1 level individually, unfortunately Bungie doesn't have a direct indication in the API aside from the xp being worth 5x the value so I decided to take the XP required to reach lvl 2 and multiply that by 5, this will result in levels 1-99 showing WELL_RESTED_LEVELS = 5 and with nextLevels being 100k xp the display XP will be 500k, and levels 100+ take 500k XP so it will set WELL_RESTED_LEVELS = 1, Bungie kinda shows this logic in game, by indicating levels 1-99 with 1 dash and 101 and beyond with 5 dashes. Ideally this change should also scale with any other changes to XP requirements that they may make in the future.

image
image

image
image

### CODE REVIEW

File: src/app/inventory/store/well-rested.ts [hunk 1]
```diff
@@ -42,8 +41,15 @@ export function isWellRested(
...
     seasonProgressionDef,
     weeklyProgress,
+    nextLevelAt,
   } = getSeasonPassStatus(defs, profileInfo, seasonPass, season);
 
+  /**
+   *  Calculate the amount of levels we need to fullfill well rested requirements
+   *  Ranks 101-110 are equiv to 5 levels each
+   */
+  const WELL_RESTED_LEVELS = (seasonProgressionDef.steps[1].progressTotal * 5) / nextLevelAt;
```
Comment (bhollis) [inline src/app/inventory/store/well-rested.ts]: Are you guaranteed to have a value at `seasonProgressionDef.steps[1]`? If not, this will cause a crash when that changes.

Comment (JAssertz) [reply src/app/inventory/store/well-rested.ts]: I think we are, but I can apply an update to have a fallback value just in case, the only time when I can imagine that value wouldn't exist is when we are changing to a new season and our player hash has changed but the season isn't visible yet?

File: src/app/inventory/store/well-rested.ts [hunk 2]
```diff
@@ -42,8 +41,16 @@ export function isWellRested(
...
     weeklyProgress,
+    nextLevelAt,
   } = getSeasonPassStatus(defs, profileInfo, seasonPass, season);
 
+  /**
+   *  Calculate the amount of levels we need to fullfill well rested requirements
+   *  Ranks 101-110 are equiv to 5 levels each
+   */
+  const BASE_LEVEL_XP_REQUIREMENT = seasonProgressionDef?.steps[1].progressTotal || 100000;
+  const WELL_RESTED_LEVELS = (BASE_LEVEL_XP_REQUIREMENT * 5) / nextLevelAt;
```
Comment (bhollis) [inline src/app/inventory/store/well-rested.ts]: These aren't global constants, they should be camelCase. Plus, you still didn't do the thing that makes this not crash:
```suggestion
  const baseLevelXPRequirement = seasonProgressionDef?.steps[1]?.progressTotal ?? 100000;
  const wellRestedLevels = (baseLevelXPRequirement * 5) / nextLevelAt;
```
