### PR TITLE
Integrate plug set collections into presentation node tree, allow search

### LINKED ISSUE #9433: Can't search for emotes on the Records page
### DIM Version

current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

On the Progress page the search bar does not search emotes, but does seem to search everything else on the page.

As an example, the Dandy Lion emote:
image

But if you put "dandy" into the search box on the Progress page, it returns nothing.
image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #9433. Theoretically we could also integrate them deeper in the presentation node tree, such as in the Collections > Flair subnode...

### CODE REVIEW

File: src/app/records/presentation-nodes.ts [hunk 1]
```diff
@@ -79,13 +95,20 @@ export interface DimPresentationNodeSearchResult extends DimPresentationNodeLeaf
...
+  node: number,
+  plugSetCollections?: { hash: number; displayItem: number }[]
 ): DimPresentationNode | null {
   const { defs, buckets, profileResponse } = itemCreationContext;
   const presentationNodeDef = defs.PresentationNode.get(node);
   if (presentationNodeDef.redacted) {
     return null;
   }
+  const commonNodeProperties = {
+    presentationNodeDef,
```
Comment (bhollis) [inline src/app/records/presentation-nodes.ts:107]: Doesn't this need to be:
```suggestion
    nodeDef: presentationNodeDef,
```

Comment (robojumper) [reply src/app/records/presentation-nodes.ts]: Good catch, types adjusted and fixed.

**Review by bhollis — APPROVED** [review]
