### PR TITLE
golf scoring for drawtime & chargetime

### LINKED ISSUE #3951: Charge Time in comparison tool incorrectly highlights high (worse) numbers as blue
Fusion rifle stat Charge Time is an instance of higher = worse, but in comparison tool both blue/green/yellow/red coloring ("best" stat) and sorting treat it as though higher is better.

image

(In this image, the Crooked Fang with Backup Plan and Charge Time masterwork is clearly the fastest of the bunch, but sorts as worst and doesn't get the blue stat color.)

### PR DESCRIPTION
**Pull request by sundevour**
closes #3951

**item comparison popup:**
adds `lowerBetter` boolean to StatInfo to track stats where a lower number is considered better in comparison
applies true to stats 447667954, 2961396640, which are associated w/ bows, FRs, LFRs

image

**item popup:**
modifies inline better/worse comparison logic which turns numbers green or red compared to equipped weapon

image

### CODE REVIEW

File: src/app/item-popup/ItemStats.tsx [hunk 1]
```diff
@@ -64,15 +64,20 @@ function ItemStatRow({
...
   const isMasterworkedStat =
     item.isDestiny2() && item.masterworkInfo && stat.statHash === item.masterworkInfo.statHash;
   const masterworkValue =
     (item.isDestiny2() && item.masterworkInfo && item.masterworkInfo.statValue) || 0;
-
   const higherLowerClasses = {
-    'higher-stats': value > compareStatValue && compareStat,
-    'lower-stats': value < compareStatValue && compareStat
+    'higher-stats':
+      ((!lowerBetter && value > compareStatValue) || (lowerBetter && value < compareStatValue)) &&
```
Comment (delphiactual) [inline src/app/item-popup/ItemStats.tsx]: 'higher-stats': !lowerBetter ? value > compareStatValue && compareStat : value < compareStatValue && compareStat;

Comment (sundevour) [reply src/app/item-popup/ItemStats.tsx]: as you wish~

File: src/app/compare/Compare.tsx [hunk 2]
```diff
@@ -426,6 +430,8 @@ function getAllStats(comparisons: DimItem[], ratings: ReviewsState['ratings']) {
         stat.min = Math.min(stat.min, itemStat.value || 0);
         stat.max = Math.max(stat.max, itemStat.value || 0);
         stat.enabled = stat.min !== stat.max;
+        // lower # is better for drawtime and chargetime stats
+        stat.lowerBetter = [447667954, 2961396640].includes(itemStat.statHash);
```
Comment (bhollis) [inline src/app/compare/Compare.tsx]: Nit: we could extract this into a shared function or constant (not a huge deal).
