### PR TITLE
Remove armour 1 from optimiser.

### LINKED ISSUE #6481: Loadout Optimizer for Hunter not working
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue? ORANGE

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari? CHROME

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem. 

Using loadout optimizer for Hunter, click on select perk, but it wont let me choose certain perks, for example I have old stompees, and it wont let me select it, among other perks. I have the exotics in my inventory as well

### PR DESCRIPTION
**Pull request by ryan-rushton**
Filtered out items that are not armour 2 in the optimiser, this lead to a bunch of cleanup where we can ignore perk choices in the ui and when calculating stats.

Renamed a few things to not reference armour2 in the name.

It would be good if my PR for removing the header buttons in the mod picker went in before this

Closes #6481

### CODE REVIEW

File: src/app/loadout-builder/utils.ts [hunk 1]
```diff
@@ -210,82 +139,25 @@ export function getFilteredPerksAndPlugSets(
...
 export function statTier(stat: number) {
   return _.clamp(Math.floor(stat / 10), 0, 10);
 }
 
 /**
- * This figures out which perks need to be selected on specific armor 1.0 items to achieve the desired stat mix.
- * process#generateMixesFromPerksOrStats uses a very similar algorithm to generate the stat mixes initially so the
- * two should be kept in sync if this changes.
- */
-export function generateMixesFromPerks(
```
Comment (bhollis) [inline src/app/loadout-builder/utils.ts:228]: Love the cleanup. I wonder if there's even more we can remove now that each item has one and only one stat set instead of having N possible mixes.

**Review by bhollis — APPROVED** [review]
Hard to pick through with the renames in with the actual changes but it looks good. One thing to think about is that now that the perk picker is basically just exotic perks, maybe we could let you just pick the exotic?

File: src/app/loadout-builder/utils.ts (hunk 1 above)
Comment (ryan-rushton) [reply src/app/loadout-builder/utils.ts:228]: I think there is, I will go digging for more.

**Comment by ryan-rushton** [comment]
The only rename I think I did was remove Armor2 from things.

File: src/app/loadout-builder/utils.ts (hunk 1 above)
Comment (ryan-rushton) [reply src/app/loadout-builder/utils.ts:228]: I think we were generating all the stat sets before but only keeping the "best" one which why you don't see much of it getting removed here. We were recalculating it if needed in the UI. The stats on ArmorSet are now just a record of stat type to a number.

File: src/app/loadout-builder/filter/PerkPicker.m.scss [hunk 2]
```diff
@@ -28,32 +28,6 @@
   margin-right: 8px;
 }
 
-.tabs {
```
Comment (ryan-rushton) [inline src/app/loadout-builder/filter/PerkPicker.m.scss:31]: Deleted as I removed the headers in the perk picker too

File: src/app/loadout-builder/filter/PerkPicker.tsx [hunk 3]
```diff
@@ -262,7 +226,28 @@ function PerkPicker({
   return (
     <Sheet
       onClose={onClose}
-      header={header}
+      header={
```
Comment (ryan-rushton) [inline src/app/loadout-builder/filter/PerkPicker.tsx:229]: Moved it and deleted the header buttons like I did in the mod picker. There aren't many perks for exotics so the buttons aren't necessary imo.

File: src/app/loadout-builder/generated-sets/GeneratedSetItem.m.scss [hunk 4]
```diff
@@ -55,20 +55,6 @@
   }
 }
 
-.altPerk {
```
Comment (ryan-rushton) [inline src/app/loadout-builder/generated-sets/GeneratedSetItem.m.scss:58]: Deleted as we no longer show alternate perks

File: src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx [hunk 5]
```diff
@@ -22,43 +21,21 @@ export default function GeneratedSetItem({
...
   locked?: readonly LockedItemType[];
   defs: D2ManifestDefinitions;
-  statValues: number[];
   itemOptions: DimItem[];
-  statOrder: StatTypes[];
-  lockedMods: LockedArmor2Mod[];
+  lockedMods: LockedMod[];
   lbDispatch: Dispatch<LoadoutBuilderAction>;
 }) {
-  const altPerks = useMemo(() => generateMixesFromPerks(item, statValues, statOrder), [
```
Comment (ryan-rushton) [inline src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx:40]: Only used for Y1 armour

File: src/app/loadout-builder/preProcessFilter.ts [hunk 6]
```diff
@@ -64,7 +64,6 @@ export function filterItems(
           (!locked || locked.every((lockedItem) => matchLockedItem(item, lockedItem))) &&
           (!lockedMods || lockedMods.every((mod) => doEnergiesMatch(mod, item))) &&
           // Filter out items that don't contain all the armour stats as they will break things.
-          statValues.every((statHash) => item.stats?.some((stat) => stat.statHash === statHash)) &&
```
Comment (ryan-rushton) [inline src/app/loadout-builder/preProcessFilter.ts:67]: Moved to the isLoadoutItem function

File: src/app/loadout-builder/processWorker/process.ts [hunk 7]
```diff
@@ -346,51 +346,6 @@ export function process(
   return { sets: flattenSets(finalSets), combos, combosWithoutCaps, statRanges };
 }
 
-const emptyStats: number[] = new Array(_.size(statHashes)).fill(0);
-
-/**
- * Generate all possible stat mixes this item can contribute from different perk options,
- * expressed as comma-separated strings in the same order as statHashes.
- */
-function getStatMix(item: ProcessItem, assumeMasterwork: boolean, orderedStatValues: number[]) {
```
Comment (ryan-rushton) [inline src/app/loadout-builder/processWorker/process.ts:355]: Used for finding Y1 armour stats, now just using the getStatValuesWithMWProcess function directly.

File: src/app/loadout-builder/types.ts [hunk 8]
```diff
@@ -71,8 +71,6 @@ export interface ArmorSet {
   readonly stats: Readonly<{ [statType in StatTypes]: number }>;
   /** For each armor type (see LockableBuckets), this is the list of items that could interchangeably be put into this loadout. */
   readonly armor: readonly DimItem[][];
-  /** The chosen stats for each armor type, as a list in the order Mobility/Resiliency/Recovery. */
-  readonly statChoices: readonly number[][];
```
Comment (ryan-rushton) [inline src/app/loadout-builder/types.ts:75]: Never actually used in the UI, only in process.

File: src/app/loadout-builder/utils.ts [hunk 9]
```diff
@@ -40,62 +21,10 @@ export function filterPlugs(socket: DimSocket) {
     return false;
   }
 
-  // Armor 2.0 mods
-  if (socket.plugged.plugDef.collectibleHash) {
```
Comment (ryan-rushton) [inline src/app/loadout-builder/utils.ts:44]: Removed all this filter stuff and instead just match on exotic perks

File: src/app/loadout-builder/utils.ts [hunk 10]
```diff
@@ -210,82 +139,25 @@ export function getFilteredPerksAndPlugSets(
   return { filteredPlugSetHashes, filteredPerks };
 }
 
-/** Whether this item is eligible for being in loadout builder */
+/** Whether this item is eligible for being in loadout builder. Now only armour 2.0 and only items that have all the stats. */
 export function isLoadoutBuilderItem(item: DimItem) {
   // Armor and Ghosts
-  return item.bucket.inArmor;
+  return (
```
Comment (ryan-rushton) [inline src/app/loadout-builder/utils.ts:145]: Moved the energy and stat filtering stuff here so we cut down as much stuff as possible, as early as possible.

**Comment by ryan-rushton** [comment]
I went through and commented on all non name/move changes to make things clearer.

**Review by bhollis — APPROVED** [review]
