### PR TITLE
Fixed issue where more than one mod can be selected for a single click.

### LINKED ISSUE #7200: clicking mod icon in LO selects 3 of that mod.
### DIM Version

current beta and app

### Browser Details

Chrome Version (current)

### OS Details

Windows 10

### Describe the bug

best illustrated by this GIF
modsBug

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ryan-rushton**
Only happens when you click on the actual image. Also happens if you try and tab around. I added blue outlines for the tabbed element as you had no idea where you were while tabbing before.

Screen Shot 2021-11-02 at 10 57 16 pm

Fixes #7200

### CODE REVIEW

File: src/app/dim-ui/ClosableContainer.m.scss [hunk 1]
```diff
@@ -18,6 +18,9 @@
   &:hover {
     background-color: $orange;
   }
+  &:focus {
+    outline: 1px solid $blue;
```
Comment (ryan-rushton) [inline src/app/dim-ui/ClosableContainer.m.scss:22]: I just picked blue as it is closer to browser defaults but it doesn't look too bad. We already use orange for selected so I wasn't going to use that.

**Review by bhollis — APPROVED** [review]
