### PR TITLE
Another mod assignment issue fix.

### LINKED ISSUE #5805: Mod assignment algorithm is off for Mod Picker.
Got a report by a user that mods assignments are off with the mod picker https://github.com/DestinyItemManager/DIM/issues/5351#issuecomment-692512011

I have messed around with this and I can get similar weird results as follows. Note that the last general mod never gets slotted.

image

### PR DESCRIPTION
**Pull request by ryan-rushton**
I think this one will fix it properly. Worst case scenario I have found is around a 10s process time. It seems to be at its worst when you have 4 general and seasonal mods locked that are unique based on the uniq algorithm in the permutation generator.

I also snuck in a sneaky css change as I was getting some chonky buttons.

Fixes #5805

### CODE REVIEW

File: src/app/loadout-builder/processWorker/processUtils.ts [hunk 1]
```diff
@@ -158,3 +157,162 @@ export function canTakeAllGeneralMods(
...
+  const cursorArray = [0, 0, 0, 0, 0];
+  const modsCopy: (ProcessMod | null)[] = [...mods];
+
+  while (modsCopy.length < 5) {
+    modsCopy.push(null);
+  }
+
+  let i = 0;
+
+  const rtn = [Array.from(modsCopy)];
```
Comment (bhollis) [inline src/app/loadout-builder/processWorker/processUtils.ts:178]: You use `[...mods]` and `Array.from(mods)` sort of interchangeably

**Review by bhollis — APPROVED** [review]

File: src/app/loadout-builder/processWorker/processUtils.ts (hunk 1 above)
Comment (ryan-rushton) [reply src/app/loadout-builder/processWorker/processUtils.ts:178]: Swapped the spread to an Array.from
