### PR TITLE
Remove mod assignments that use process utils.

### LINKED ISSUE #6872: Loadout Optimizer unnecessarily prefers to change armors element type to fit mod selection
**What version of DIM are you using?**
Version 6.70.0.1000556 (beta), built on 6/23/2021, 9:16:17 AM

**What Browser and OS are you using?**
Microsoft Edge 91.0.864.54

**Describe the bug and how to make it happen**
1. Open "Loadout Optimizer"
2. Select "Ascendant Shard" from "what you will spend" dropdown
3. Pin a loadout such that you have only at least 2 arc affinity items and that either helmet or arms or both are not arc
4. Select "Radiant Light" and "Powerful Friends" mods

Expected:
Mods are slotted into already available Arc affinity armor

Actual:
Mods are slotted into Helmet and Arms regardless of their affinity
image

Note that as long as you don't select "Ascendant Shard" as something you'd be willing to spend mods are placed as expected (if possible) however this makes it difficult to compare loadouts between things you've already masterworked vs things you are willing to masterwork. This is a regression of behavior with what was possible with the "Assume masterworked" checkbox

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
JQMIGRATE: Migrate is installed, version 3.0.0
instrument.ts:129 [app] DIM v6.70.0.1000556 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:129 [dim sync] globalSettings Object
log.ts:44 Load manifest: 1632.14501953125 ms
log.ts:44 Process inventory: 160.87890625 ms
log.ts:44 Inventory state update: 86.13720703125 ms
optimizer:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
instrument.ts:129 [dim sync] Saving profile data to IDB
​ [loadout optimizer] found 200 stat mixes after processing 186732 stat combinations in 309 ms -  604310.6796116505 combos/s [object Object] [object Object]
instrument.ts:129 [loadout optimizer] useProcess: worker time 363.70000000018626ms
instrument.ts:129 [loadout optimizer] useProcess 405.89999999990687ms
DevTools failed to load source map: Could not load content for chrome-extension://eobkhgkgoejnjaiofdmphhkemmomfabg/libs/jquery.qtip.min.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
114-5f4e09.js:1 [loadout optimizer] found 1 stat mixes after processing 1 stat combinations in 0.5 ms -  2000 combos/s {numCantSlotMods: 0, numSkippedLowTier: 0, numStatRangeExceeded: 0} {numInserted: 1, numRejectedAfterInsert: 0, numDoubleExotic: 0}
instrument.ts:129 [loadout optimizer] useProcess: worker time 102.10000000009313ms
instrument.ts:129 [loadout optimizer] useProcess 146.20000000018626ms
114-5f4e09.js:1 [loadout optimizer] found 1 stat mixes after processing 1 stat combinations in 1.1000000000931323 ms -  909.0909090139403 combos/s {numCantSlotMods: 0, numSkippedLowTier: 0, numStatRangeExceeded: 0} {numInserted: 1, numRejectedAfterInsert: 0, numDoubleExotic: 0}
instrument.ts:129 [loadout optimizer] useProcess: worker time 49.60000000009313ms
instrument.ts:129 [loadout optimizer] useProcess 66.6999999997206ms
```

### PR DESCRIPTION
**Pull request by ryan-rushton**
This removes mod assignments created from using the process code and cleans up the assignments from the process functions.

Closes #6872

<pr-train-toc>

|     | PR    | Description                                                                                                     |
| --- | ----- | --------------------------------------------------------------------------------------------------------------- |
| 👉  | #7030 | Remove mod assignments that use process utils. |
|     | #7031 | Create new mod assignment function.                     |
|     | #7032 | Added hacky unassigned mods calculation.                                                                        |

</pr-train-toc>

### CODE REVIEW

File: src/app/loadout-builder/LoadoutBuilder.tsx [hunk 1]
```diff
@@ -375,16 +375,14 @@ function LoadoutBuilder({
           <GeneratedSets
             sets={filteredSets}
             lockedMap={lockedMap}
+            lockedMods={lockedMods}
```
Comment (bhollis) [inline src/app/loadout-builder/LoadoutBuilder.tsx:378]: uhhh, might have some merge conflicts incoming

**Review by bhollis — APPROVED** [review]

File: src/app/loadout-builder/LoadoutBuilder.tsx (hunk 1 above)
Comment (ryan-rushton) [reply src/app/loadout-builder/LoadoutBuilder.tsx:378]: Yeah that is cool, get your stuff in and I will sort them out.
