### PR TITLE
Load manifest from multiple files and reduce memory usage.

### LINKED ISSUE #5095: Switch to using file-per-table JSON manifest
Today we load one big manifest, which is now 112MB uncompressed. We don't need every table though, and there are now individual files per table. Downloading many files is trickier and likely slower to download, plus it gives far more opportunities for failure, but it may help with clients that crash trying to load so much JSON at once.

Note that even just the InventoryItem JSON file is 54MB, so to further reduce we'd need to trim the contents, not just which tables we load. There's a lot that could be dropped, but trimming contents is likely best done via the DIM API.

### PR DESCRIPTION
**Pull request by bhollis**
This makes two big changes to manifest loading:

1. We now load individual files per-table and stitch them together, instead of loading the mega combined JSON and stripping out what we don't want. This should reduce peak memory usage and help avoid crashes on Chrome.
2. Carefully trim down the InventoryItem table before saving it to cache or using it further, reducing total memory usage. This can't reduce the peak memory usage of this table (~61MB) but it reduces the sustained memory cost and the cost on subsequent loads (from cache) to about 27MB (a 56% reduction). I've only removed properties we weren't using.

Load times are about the same or slightly better (I had messed up my measurement before). However, now there are many more opportunities for one file failing to download to kill the whole app load.

Fixes #5095

### CODE REVIEW

File: src/app/manifest/manifest-service-json.ts [hunk 1]
```diff
@@ -24,6 +25,44 @@ export interface ManifestServiceState {
...
+        def.preview.derivedItemCategories = emptyArray();
+      }
+      if (def.inventory.bucketTypeHash !== 3284755031) {
+        def.talentGrid = emptyObject();
+      }
+
+      if (def.sockets) {
+        def.sockets.intrinsicSockets = emptyArray();
+        for (const socket of def.sockets.socketEntries) {
+          if (socket.reusablePlugSetHash && socket.reusablePlugItems.length > 0) {
```
Comment (sundevour) [inline src/app/manifest/manifest-service-json.ts:55]: is the assumption here that we can empty out `reusablePlugItems` and use `reusablePlugSetHash` to fetch the same data? maybe i am missing something but it doesn't seem like there's logic to do that.

does removing all `reusablePlugItems` entries break this? https://github.com/DestinyItemManager/DIM/blob/ed62ef58924a8c27f804ba67ba763d6737da15cb/src/app/inventory/store/sockets.ts#L225

Comment (bhollis) [reply src/app/manifest/manifest-service-json.ts:55]: I think it still works - I'm using `reusablePlugSetHash` to show options in the mod viewer, but no longer populating the options on the socket itself. Generally we're using the reusable plugs from the live profile data instead of the manifest definitions, so everything displays right.

The only place we could have been using this is in Collections, but it appears we weren't making use of that there in the first place.

The main reason this is important is that the definitions currently include a list of every masterwork mod (100 entries) for every item that could be masterworked.

Comment (bhollis) [reply src/app/manifest/manifest-service-json.ts:55]: Let me fix this up separately.
