### PR TITLE
cross-platform https dev server

### LINKED ISSUE #3172: CONTRIBUTING.md Missing Instructions for OpenSSL
Hello!

I am not sure if I missed it somewhere, but I did not see any instructions explaining the requirements for OpenSSL. When I was going through the [Install Pre-requisites](https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md#pre-requisites) section on my **Windows 10 system**, all was well until I ran `yarn start`. I received the following error:

Error Message: `'openssl' is not recognized as an internal or external command`

You can see more detail in the screenshot below.

yarn_start_error_openssl

Turns out that I did not have OpenSSL installed on this machine...

What I did to resolve my issue:
1. Downloaded the binaries from [here](https://slproweb.com/products/Win32OpenSSL.html) - **Win64 OpenSSL v1.1.1 EXE**
2. Installed Win64OpenSSL-1_1_1.exe to `C:\Program Files\OpenSSL-Win64`
3. Opened CMD as Administrator
4. Ran the command: `"C:\Program Files\OpenSSL-Win64\bin\openssl.exe"`
5. Ran the command that failed during **yarn start**: `req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem -subj '/CN=www.mydom.com/O=My Company Name LTD./C=US'` - (not sure if this command is different per user)
6. Ran `yarn start`

See successful example below:

yarn_start_error_fix

I hope this information was helpful and not redundant. I am new to open source and appreciate the documentation that is available to help me get started very much!

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
This PR replaces the now-deprecated `webpack-serve` with the (no-longer deprecated) `webpack-dev-server` module. This change allows us to use wds's built in cert generation capabilites (stemming from [selfsigned](https://npmjs.org/package/selfsigned) and [node-forge](https://npmjs.org/packages/node-forge)) which should work cross-platform, eliminating the need for the developer to manually install openssl. 

fixes #3172

### CODE REVIEW

File: config/webpack.js [hunk 1]
```diff
@@ -56,18 +50,10 @@ module.exports = (env) => {
       chunkFilename: isDev ? '[name]-[hash].js' : '[name]-[contenthash:6].js'
     },
 
-    // Dev server
-    serve: process.env.WEBPACK_SERVE
-      ? {
-          devMiddleware: {
-            stats: 'errors-only'
```
Comment (bhollis) [inline config/webpack.js]: Can you make sure we still have the minimal stats printing out with the dev server? It shouldn't print out a bunch of info about the compiled modules.

Comment (LongLiveCHIEF) [reply config/webpack.js]: Done!

**Comment by bhollis** [comment]
Awesome, thanks!
