### PR TITLE
Autocomplete Jötunn

### LINKED ISSUE #9300: Item names with umlauts don't appear in the auto-complete list
### DIM Version

current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

The toaster is hard to search for.

Internally is is name:jötunn but the o umlaut (ö) is something I can't work out how to type.  However DIM is clever and has aliased this to jotunn without the umlaut.  But not everywhere.

If I start typing a query with jot (see screencap below) it does highlight jötunn, but it is not presented in the autocomplete list.

image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #9300.

grafik
->
grafik

### CODE REVIEW

File: src/app/search/armory-search.ts [hunk 1]
```diff
@@ -63,10 +68,13 @@ export const buildArmoryIndex = memoizeOne((defs: D2ManifestDefinitions) => {
...
 export function getArmorySuggestions(
   armoryIndex: ArmoryEntry[] | undefined,
-  query: string
+  query: string,
+  language: DimLanguage
 ): ArmorySearchItem[] {
   const armoryEntries = query.length
-    ? armoryIndex?.filter((armoryItem) => armoryItem.name.toLocaleLowerCase().includes(query))
+    ? armoryIndex?.filter((armoryItem) =>
+        armoryItem.plainName.includes(plainString(query, language))
```
Comment (bhollis) [inline src/app/search/armory-search.ts:76]: Move `plainString(query, language)` out of the filter loop to avoid recomputation.

**Review by bhollis — APPROVED** [review]
