### PR TITLE
is:curated needed more null checks

### LINKED ISSUE #4009: is:curated throws exception
breadcrumbs.ts:111 TypeError: Cannot read property 'plugCategoryHash' of undefined
    at search-filters.ts:1256
    at Array.filter (<anonymous>)
    at Object.curated (search-filters.ts:1252)
    at search-filters.ts:670
    at Array.every (<anonymous>)
    at search-filters.ts:658
    at Array.filter (<anonymous>)
    at Object.render (SearchFilter.tsx:144)
    at So (react-dom.production.min.js:173)
    at Co (react-dom.production.min.js:172)
    at react-dom.production.min.js:180
    at Ya (react-dom.production.min.js:232)
    at Va (react-dom.production.min.js:233)
    at Ns (react-dom.production.min.js:249)
    at Ts (react-dom.production.min.js:248)
    at Is (react-dom.production.min.js:250)
    at Object.notify (Subscription.js:23)
    at e.t.notifyNestedSubs (Subscription.js:65)
    at t.n.notifySubscribers (Provider.js:59)
    at e.t.handleChangeWrapper (Subscription.js:70)
    at m (redux.js:220)
    at index.js:11
    at w.<anonymous> (redux.js:475)
    at b (debounce.js:95)
    at w (debounce.js:144)
    at j (debounce.js:132)
    at r (helpers.ts:85)

### PR DESCRIPTION
**Pull request by delphiactual**
Closes #4009

### CODE REVIEW

File: src/app/search/search-filters.ts [hunk 1]
```diff
@@ -1253,6 +1253,9 @@ function searchFilters(
               (socket) =>
                 socket &&
                 socket.plug &&
+                socket.plug.plugItem &&
+                socket.plug.plugItem.plug &&
+                socket.plug.plugItem.plug.plugCategoryHash &&
```
Comment (bhollis) [inline src/app/search/search-filters.ts]: This can now be written as `idx(socket, (s) => s.plug.plugItem.plug.plugCategoryHash)`
