### PR TITLE
Fix icon watermark scaling at reduced item sizes

### LINKED ISSUE #8491: big watermarks in small icons
[app] DIM v7.21.0.1001807 (beta

seems pretty recent. see bottom row here
image

### PR DESCRIPTION
**Pull request by vivekhnz**
This PR fixes a regression introduced by 122165d for #8478 and will close #8491.

dim-fix-icon-overlay-scaling

### CODE REVIEW

**Review by nev-r — APPROVED** [review]

File: src/app/inventory/ItemIcon.m.scss [hunk 1]
```diff
@@ -92,6 +92,12 @@ $commonBg: #366f42;
   height: calc(var(--item-size) - #{2 * $item-border-width});
   width: calc(var(--item-size) - #{2 * $item-border-width});
   position: absolute;
+
+  // Ensure that the contained image is correctly scaled down in cases where --item-size is reduced
+  // e.g. Loadout Optimizer Exotic armor picker, Loadout Fashion Mods, Loadout Organizer perk columns
+  & > img {
+    width: 100%;
+  }
```
Comment (bhollis) [inline src/app/inventory/ItemIcon.m.scss:100]: Not sure I understand how this would work - the iconOverlay class is applied to the `img` itself now, it shouldn't have an `img` as a child.

If `--item-size` is changed, why wouldn't the existing calculations based on `--item-size` handle it?

Comment (vivekhnz) [reply src/app/inventory/ItemIcon.m.scss]: Ahh, good catch. The real reason this broke is that `ItemIcon`'s DOM was flattened but `DefItemIcon`'s was not. I've reverted the above scaling change, removed the `div` that surrounds the overlay image (same change as what was done for #8478) and confirmed the issue is fixed.

**Review by bhollis — APPROVED** [review]
