### PR TITLE
Stat preview

### LINKED ISSUE #7073: Armory followups
### Proposed change

I love the new item detail popup.

Please consider adding the following features/fixes:
- The link to DestinyTracker used to include all the selected perks too. Please add this again.
- The new link to Light.gg could also include the perks.
- Please add a link to D2 Gunsmith (with perks) too. This is really useful for checking range.
- Please highlight the perk icons of the current item.
- If possible highlight the wishlisted perks similar to how Little Light does.

### How does this fit into your workflow?

I often click on a weapon and then click through to see what the possible god rolls are according to other sites. I also wrote my own TamperMonkey script to view the item in D2 Gunsmith to see the calculated range. (Which of course now no longer works).

### LINKED ISSUE #7084: Armory permalink doesn't work

### PR DESCRIPTION
**Pull request by bhollis**
This replaces the stat preview code in Compare with a new approach, where you can generate new copies of items with different perks selected (and stats updated to reflect those perks). This unwinds all the special casing that old implementation caused, and most components don't need to know anything special.

With that in hand I've made "click on a perk to select it and preview its stat effects" work:

1. In Compare as it always did
2. In the item popup, both with list-style and grid-style perks lists.
3. In Organizer, from the "Perks, Mods & Shaders" column.
4. In the Armory, to see the effects of any perk the item can roll with.

On the Armory page, I also made some changes to highlight perks that can no longer roll, remove weird duplicate entries, and fix the DIM permalink so you can share rolls. This fixes #7084. Clicking into Armory from an item also now starts with that item's selected perks highlighted. 

I've set the stat values to animate (count up or down) to their new value - it's a nice way to call attention to them on the Compare and Organizer page. On the item popup and Armory the stat bars also animate:
stat-preview

Fixes #7073

### CODE REVIEW

File: src/app/inventory/store/stats.ts [hunk 1]
```diff
@@ -98,9 +98,9 @@ type StatLookup = { [statHash: number]: DimStat | undefined };
 
 /** Build the full list of stats for an item. If the item has no stats, this returns null. */
 export function buildStats(
+  defs: D2ManifestDefinitions,
   createdItem: DimItem,
-  itemDef: DestinyInventoryItemDefinition,
-  defs: D2ManifestDefinitions
+  itemDef = defs.InventoryItem.get(createdItem.hash)
```
Comment (nev-r) [inline src/app/inventory/store/stats.ts:103]: any reason to retain this param when it can be so quickly re-derived? feels ripe for cleanup

File: src/app/item-popup/ItemPerksList.tsx [hunk 2]
```diff
@@ -126,7 +128,9 @@ function PerkPlug({
     <div
       key={plug.plugDef.hash}
       className={clsx(styles.plug, {
-        [styles.plugged]: plug === socketInfo.plugged,
+        [styles.plugged]: socketInfo.actuallyPlugged
+          ? plug === socketInfo.actuallyPlugged
+          : plug === socketInfo.plugged,
```
Comment (nev-r) [inline src/app/item-popup/ItemPerksList.tsx:133]:
```suggestion
        [styles.plugged]: plug === (socketInfo.actuallyPlugged ?? socketInfo.plugged),
```

File: src/app/item-popup/ItemSocketsGeneral.tsx [hunk 3]
```diff
@@ -19,25 +18,19 @@ interface Props {
...
   const defs = useD2Definitions();
   const wishlistRoll = useSelector(wishListSelector(item));
   const [socketInMenu, setSocketInMenu] = useState<DimSocket | null>(null);
 
   const handleSocketClick = (item: DimItem, socket: DimSocket, plug: DimPlug, hasMenu: boolean) => {
     if (hasMenu) {
       setSocketInMenu(socket);
-    } else if (updateSocketComparePlug) {
-      updateSocketComparePlug({
+    } else if (onPlugClicked) {
```
Comment (nev-r) [inline src/app/item-popup/ItemSocketsGeneral.tsx:32]: matter of taste but i like
```
    } else {
      onPlugClicked?.({
        item,
        socket,
        plug,
      });
```

because this `else if` isn't really related to the original `if (hasMenu`
it's more of an `else`. then an unrelated `if` to check if there's a function.

File: src/app/item-popup/ItemSocketsWeapons.tsx [hunk 4]
```diff
@@ -28,25 +27,19 @@ interface Props {
...
   const defs = useD2Definitions();
   const wishlistRoll = useSelector(wishListSelector(item));
   const [socketInMenu, setSocketInMenu] = useState<DimSocket | null>(null);
 
   const handleSocketClick = (item: DimItem, socket: DimSocket, plug: DimPlug, hasMenu: boolean) => {
     if (hasMenu) {
       setSocketInMenu(socket);
-    } else if (updateSocketComparePlug) {
-      updateSocketComparePlug({
+    } else if (onPlugClicked) {
```
Comment (nev-r) [inline src/app/item-popup/ItemSocketsWeapons.tsx:41]: same here

**Review by nev-r — APPROVED** [review]
image

should maybe format that text or add an extra line break, and long term we should float these perks to top or bottom of the list

File: docs/CHANGELOG.md [hunk 5]
```diff
@@ -1,5 +1,13 @@
 ## Next
 
+* Clicking perks in the item popup now changes the stats for the item to reflect the effects of switching to that perk.
+* Clicking perks in the Organizer view also changes the stats for that item.
+* Changes to th Armory view (when you click an item's title):
+  * The perks on the item you clicked from are highlighted.
+  * You can click on other perk options to preview their stat effects.
+  * You can click the "DIM" link to open the item info on its own, and share a roll with others.
```
[the remark this answers is not in the document]
Comment (bhollis) [reply docs/CHANGELOG.md:8]: Fixed the weird URL bug. The link does not work when not logged in, but it definitely would be nice if it did - that'll take some extra work. You can share the URL and it'll redirect to your logged in user though, even if it has your own profile ID in it.

File: src/app/inventory/item-types.ts [hunk 6]
```diff
@@ -363,13 +363,23 @@ export interface DimPlug {
...
   socketIndex: number;
   /** The currently inserted plug item, if any. */
   plugged: DimPlug | null;
+
+  /**
+   * If the "plugged" plug has been overridden by SocketOverrides, this captures
+   * which plug option is actually still plugged on the item, even though we're
+   * viewing an alternative.
+   */
+  actuallyPlugged?: DimPlug;
```
[the remark this answers is not in the document]
Comment (bhollis) [reply src/app/inventory/item-types.ts:381]: Yeah, that was my original thought, but by doing it this way we don't have to go around making every bit of code check `plugOverride` - anything that knows `plugged` works with the new plug, and the only things that needed to change were a couple places that know how to display that it's been overridden.

File: src/app/inventory/store/stats.ts (hunk 1 above)
Comment (bhollis) [reply src/app/inventory/store/stats.ts:103]: Not really, it's just already there for most invocations.
