### PR TITLE
DTR fixes

### LINKED ISSUE #4544: Perks query param linking to DTR DB has a bug
I noticed you guys added the perks param to the DTR DB links, however there's a small bug with it.

The query param itself is prefixed with `&`, this should be `?` as its the first param. Secondly when an item doesn't have any perks the url is suffixed with `null`.  Which leads to these kind of links: `https://destinytracker.com/destiny-2/db/items/2526736322null`.

### PR DESCRIPTION
**Pull request by delphiactual**
Closes #4544

### CODE REVIEW

**Comment by delphiactual** [comment]
@48klocs @sgtfrankieboy done from my phone at lunch please review

File: src/app/item-popup/ItemPopupHeader.tsx [hunk 1]
```diff
@@ -151,11 +151,11 @@ function destinyDBLink(item: DimItem) {
     const perkCsv = buildPerksCsv(d2Item);
 
     if (perkCsv && perkCsv.length > 0) {
-      perkQueryString = `&perks=${perkCsv}`;
+      perkQueryString = `?perks=${perkCsv}`;
     }
   }
 
-  return `https://destinytracker.com/destiny-2/db/items/${item.hash}${perkQueryString}`;
+  return `https://destinytracker.com/destiny-2/db/items/${item.hash}${perkQueryString ? perkQueryString : ''}`;
```
Comment (48klocs) [inline src/app/item-popup/ItemPopupHeader.tsx]: I should have just init'd `perkQueryString` to a sane (empty string) default instead of making us jump through hoops here.
