### PR TITLE
Fix for incorrect inactive plug stats.

### LINKED ISSUE #6653: Mod stat calculations not using the right values
Not sure if this changed recently (@ryan-rushton?) but we're calculating mod stats wrong now by using the post-capped version instead of the pre-capped version.

From an example in Discord:

The problem here is that when not equipped, Extended Barrel shows +6 Recoil instead of +10 Recoil. Once equipped, it shows +10 Recoil.

Without either mod the stat is 74. The problem is that the +30 for Arrowhead Brake becomes +26 because of the 100 stat cap. When we try to figure out what Extended Barrel would be, we subtract the contribution of the equipped mod (Arrowhead Brake) which would be 104-26 = 78 (but we should really subtract 30!). Separately we calculate what the stat would be with Extended Barrel, which is +10 so you get a total of 84. ). That results in 84 - 78 = +6. I think the problem is that the number we're using to subtract a mod's effect is the post-capped version, when it should be the original version (this may have changed sometime recently).

### PR DESCRIPTION
**Pull request by ryan-rushton**
With fix

On beta

Just to note I had a click around my weapons and armour and everything looked as expected. It should only really effect inactive plugs on weapons if my understanding is correct, it will effect other plugs but I don't think they are visible..

Fixes #6653

### CODE REVIEW

**Review by nev-r — APPROVED** [review]

File: src/app/inventory/store/stats.ts [hunk 1]
```diff
@@ -389,46 +389,102 @@ function enhanceStatsWithPlugs(
...
+  // interpolate each plugs effect on the item.
+  const baseItemInvestmentStats: { [statHash: number]: number } = {};
+
+  if (activePlug) {
+    const insertedPlugStats: {
+      [statHash: number]: number;
+    } = {};
+
+    for (const perkStat of activePlug.plugDef.investmentStats) {
+      let value = perkStat.value;
```
Comment (bhollis) [inline src/app/inventory/store/stats.ts:418]: I'd love if this could be renamed `perkInvestmentValue` or something

File: src/app/inventory/store/stats.ts [hunk 2]
```diff
@@ -389,46 +389,102 @@ function enhanceStatsWithPlugs(
...
-      const valueWithoutPerk = Math.min(itemStat.investmentValue - value, itemStat.maximumValue);
-      value = itemStat.value - valueWithoutPerk;
+  // The plug that is currently inserted into the socket
+  const activePlug = socket.plugged;
+
+  // We need to calculate the base investment stat value for the item so we can correctly
+  // interpolate each plugs effect on the item.
+  const baseItemInvestmentStats: { [statHash: number]: number } = {};
+
+  if (activePlug) {
```
Comment (bhollis) [inline src/app/inventory/store/stats.ts:412]: I'd love some more comments that explain how the active plug is being pulled out and treated separately.

Comment (ryan-rushton) [reply src/app/inventory/store/stats.ts:412]: Yup, I'll come back and revisit this once @nev-r is finished with the stat rework. I don't think it will be needed though from the sounds of that change as this will likely be gone.

Comment (bhollis) [reply src/app/inventory/store/stats.ts:412]: Why would this be gone? This is about stats from plugs which still exist.

Comment (ryan-rushton) [reply src/app/inventory/store/stats.ts:412]: More so changed, I was talking to nev yesterday and they are going to rework a bunch of it. I think I was the commits in the other branch already.

Comment (nev-r) [reply src/app/inventory/store/stats.ts:412]: i didnt re-logic much of this particular function, but we can get stats.ts changes settled then revisit

Comment (ryan-rushton) [reply src/app/inventory/store/stats.ts:412]: Yup also just as an fyi, calculating the items base investment stats and then just looping over all the plugs would be cleaner but there is a few more loops involved. I went with this method, even though its not as intuitive, as it should be slightly more performant. Happy to revisit this and do it the other way if you two think it won't have much of an impact though.

Comment (bhollis) [reply src/app/inventory/store/stats.ts:412]: This is fine I just want enough comments to remember why it's weird

Comment (ryan-rushton) [reply src/app/inventory/store/stats.ts:412]: Easy done, I will sort it out once nevs stuff is in
