### PR TITLE
Fixed an error where a character can have no loadout builder items.

### LINKED ISSUE #6844: loadout builder undefined error
`itemsForClass` can apparently be undefined :open_mouth: 
https://github.com/DestinyItemManager/DIM/blob/9077c3b21068ada77d3362557e2437a3b29425bc/src/app/loadout-builder/LoadoutBuilder.tsx#L201

### PR DESCRIPTION
**Pull request by ryan-rushton**
Fixes #6844

### CODE REVIEW

File: src/app/loadout-builder/LoadoutBuilder.tsx [hunk 1]
```diff
@@ -69,31 +69,36 @@ type Props = ProvidedProps & StoreProps;
 
 function mapStateToProps() {
   /** Gets items for the loadout builder and creates a mapping of classType -> bucketHash -> item array. */
-  const itemsSelector = createSelector(allItemsSelector, (allItems): Readonly<{
```
Comment (ryan-rushton) [inline src/app/loadout-builder/LoadoutBuilder.tsx:72]: I've been getting some weird formatting changing coming from the git hook lately. It seems my vscode formatting clashes with it.

Comment (ryan-rushton) [reply src/app/loadout-builder/LoadoutBuilder.tsx:72]: Looking at it, I think pretty-quick is not respecting the `.prettierrc` file...maybe. If i delete the line width config in `.prettierrc` (so it uses default 80), I get this same change happening. This line is 80 chars plus a character return.

Comment (ryan-rushton) [reply src/app/loadout-builder/LoadoutBuilder.tsx:72]: Actually it might be an update to vs code and thus the prettier extensions. Now this formatting is respected by vs code on save since the restart and update.

**Review by nev-r — APPROVED** [review]
